/**
 * English — the source of truth.
 *
 * `pt.ts` and `fr.ts` are typed against this object, so adding a key here
 * breaks the build until both translations exist. That is the point: a missing
 * translation should stop a release, not quietly show English to somebody who
 * does not read it.
 *
 * Conventions
 *   • Keys are `area.screen.thing`. `common.*` and `ui.*` are shared.
 *   • `{name}` is substituted verbatim. `{count}` also selects the plural form.
 *   • A value that changes with a number is written `{ one, other }` — never
 *     `"{count} item(s)"`, and never an English 's' bolted on in code.
 *   • Sentences are whole. Never assemble one from fragments in JSX: word
 *     order is not universal, and neither is where the number goes.
 */

export const en = {
  /* --------------------------------------------------------- common --- */
  'common.loading': 'Loading…',
  'common.retry': 'Try again',
  'common.cancel': 'Cancel',
  'common.save': 'Save',
  'common.close': 'Close',
  'common.clear': 'Clear',
  'common.search': 'Search',
  'common.back': 'Back',
  'common.signOut': 'Sign out',
  'common.signIn': 'Sign in',
  'common.optional': 'Optional',
  'common.none': 'None',
  'common.appearance': 'Appearance',
  'common.language': 'Language',
  'common.somethingWrong': 'Something went wrong. Please try again.',
  'common.offline': 'Could not reach the server. Please try again.',

  /* -------------------------------------------------------- settings --- */
  'theme.dark': 'Dark',
  'theme.light': 'Light',
  'theme.system': 'System',
  'lang.choose': 'Choose a language',
  'lang.changed': 'Language changed',
  'lang.changedBody': 'The interface is now in English.',

  /* ---------------------------------------------------------- status --- */
  'status.overdue': 'Overdue',
  'status.overdue.short': 'Overdue',
  'status.today': 'Due today',
  'status.today.short': 'Today',
  'status.soon': 'Due this week',
  'status.soon.short': 'This week',
  'status.later': 'Scheduled',
  'status.later.short': 'Later',

  /* ------------------------------------------------------------- due --- */
  'due.overdue': { one: '1 day overdue', other: '{count} days overdue' },
  'due.today': 'Due today',
  'due.tomorrow': 'Due tomorrow',
  'due.inDays': { one: 'Due in 1 day', other: 'Due in {count} days' },
  'due.overdueShort': { one: '{count}d late', other: '{count}d late' },
  'due.earlyShort': { one: '{count}d early', other: '{count}d early' },
  'due.onTheDay': 'On the day',

  /* --------------------------------------------------------- urgency --- */
  'urgency.overdue': { one: '1 overdue', other: '{count} overdue' },
  'urgency.today': { one: '1 due today', other: '{count} due today' },
  'urgency.soon': { one: '1 due this week', other: '{count} due this week' },
  'urgency.clear': 'Nothing needs attention right now',
  'urgency.notLate': 'Nothing is late — {list}',
  'urgency.and': '{list} and {last}',

  /* ------------------------------------------------ shared components --- */
  'ui.field.optional': 'Optional',
  'ui.field.required': 'Required',
  'ui.photo.take': 'Take a photo',
  'ui.photo.choose': 'Choose a photo',
  'ui.photo.retake': 'Replace photo',
  'ui.photo.uploading': 'Uploading…',
  'ui.photo.failed': 'That photo could not be uploaded. Try again.',
  'ui.photo.tooBig': 'That image is too large. Take a new photo and try again.',
  'ui.photo.wrongType': 'That file is not an image. A photo of the work is required.',
  'ui.photo.attached': 'Photo attached',
  'ui.photo.remove': 'Remove photo',
  'ui.state.emptyTitle': 'Nothing here yet',
  'ui.state.errorTitle': 'Something went wrong',
  'ui.pull.release': 'Release to refresh',
  'ui.pull.refreshing': 'Refreshing…',

  /* ------------------------------------------- errors, by server code --- */
  'error.UNAUTHORIZED': 'Your session has ended. Please sign in again.',
  'error.FORBIDDEN': 'You do not have permission to do that.',
  'error.NOT_FOUND': 'That is no longer there.',
  'error.ALREADY_COMPLETED': 'Already completed — someone got to this one first.',
  'error.EQUIPMENT_INACTIVE': 'That equipment has been deactivated. Nothing to submit.',
  'error.RULE_INACTIVE': 'That maintenance task has been deactivated. Nothing to submit.',
  'error.RULE_NOT_APPLICABLE': 'That maintenance no longer applies to this item. Nothing to submit.',
  'error.PHOTO_REQUIRED': 'A photo of the completed work is required.',
  'error.PHOTO_REUSED': 'That photo is already attached to another completion.',
  'error.DUPLICATE_CODE': 'That asset code is already in use.',
  'error.DUPLICATE_NAME': 'That name is already in use.',
  'error.TYPE_IN_USE': 'That type still has equipment on it.',
  'error.CONFIRMATION_REQUIRED': 'Please confirm before continuing.',
  'error.TOO_MANY_ATTEMPTS': 'Too many attempts. Please wait a moment and try again.',
  'error.PAYLOAD_TOO_LARGE': 'That file is too large.',
  'error.BAD_UPLOAD': 'That upload could not be read. Please try again.',
  'error.BAD_JSON': 'That request could not be read. Please try again.',
  'error.VALIDATION': 'Please check the highlighted field.',
  'error.INTERNAL': 'Something went wrong on the server. Please try again.',
  'error.SIGN_IN': 'That email and password do not match an account.',

  /* ------------------------------- field, unit and role names --- */
  'field.typeName': 'Type name',
  'field.assetCode': 'Asset code',
  'field.equipmentName': 'Equipment name',
  'field.equipmentType': 'Equipment type',
  'field.taskTitle': 'Task title',
  'unit.days': 'days',
  'unit.weeks': 'weeks',
  'unit.months': 'months',
  'unit.years': 'years',
  'role.admin': 'administrator',
  'role.worker': 'worker',

  /* ----------------------- messages the server sends, by key --- */
  'server.required': '{field} is required.',
  'server.tooLong': '{field} must be {max} characters or fewer.',
  'server.typeNameTaken': 'An equipment type called “{name}” already exists.',
  'server.typeGone': 'That equipment type no longer exists.',
  'server.typeInUse': {
    one: '1 piece of equipment still uses this type. Move or archive it first.',
    other: '{count} pieces of equipment still use this type. Move or archive them first.',
  },
  'server.badFirstDue': 'First due date must be a real calendar date.',
  'server.pickRealType': 'Pick an equipment type that still exists.',
  'server.pickRealDate': 'Pick a real calendar date.',
  'server.codeTaken': 'Asset code “{code}” is already in use.',
  'server.equipmentGone': 'That equipment no longer exists.',
  'server.intervalWhole': 'The interval must be a whole number greater than zero.',
  'server.intervalUnit': 'The interval unit must be days, weeks, months or years.',
  'server.intervalCapped': 'Intervals are capped at about fifty years, which in {unit} is {max}.',
  'server.ruleGone': 'That maintenance task no longer exists.',
  'server.taskGone': 'That task no longer exists.',
  'server.taskNotOutstanding': 'That task is no longer outstanding.',
  'server.completionGone': 'That completion record no longer exists.',
  'server.alreadyCompleted': 'Already completed — someone got to this one first.',
  'server.equipmentDeactivated': '{name} has been deactivated. Nothing to submit.',
  'server.ruleDeactivated': '“{title}” has been deactivated. Nothing to submit.',
  'server.ruleNotApplicable': '{name} is no longer a “{title}” item. Nothing to submit.',
  'server.photoRequired': 'A photo of the completed work is required.',
  'server.photoMissing': 'That photo upload could not be found. Please attach it again.',
  'server.photoNotYours': 'That photo was uploaded by someone else.',
  'server.photoReused': 'That photo is already attached to another completion.',
  'server.photoUnavailable': 'That photo is not available.',
  'server.photoOtherCompletion': 'That photo belongs to another completion.',
  'server.noPhotoAttached': 'No photo was attached.',
  'server.badUpload': 'That upload could not be read. Please attach the photo again.',
  'server.adminOnly': 'This action is for administrators only.',
  'server.roleOnly': 'This action is for {role}s only.',
  'server.wrongApp': 'This is the administrator app. Please use the worker app to sign in.',
  'server.tickConfirm': 'Tick “Maintenance completed” before submitting.',
  'server.addOnePhoto': 'Add one photo of the completed work.',
  'server.signInToContinue': 'Sign in to continue.',
  'server.noAccess': 'You do not have access to this action.',
  'server.notFound': 'That is no longer there.',


  /* ------------------------------------ the worker account sheet --- */
  'worker.account.title': 'Your account',
  'worker.account.open': 'Account, language and appearance',


  /* ------------------------------------ ui/components/PhotoCapture.tsx --- */
  'ui.photo.defaultLabel': 'Photo of the completed work',
  'ui.photo.previewAlt': 'The photo you are about to submit',

  /* ----------------------------------------- ui/components/Toaster.tsx --- */
  'ui.toast.dismiss': 'Dismiss',

  /* ------------------------------------------ ui/components/charts.tsx --- */
  'ui.chart.valueTooltip': '{label}: {value}',

  /* --------------------------------------- admin/components/Chrome.tsx --- */
  'admin.nav.sections': 'Sections',
  'admin.nav.overview': 'Overview',
  'admin.nav.overview.hint': 'Everything at a glance',
  'admin.nav.outstanding': 'Outstanding',
  'admin.nav.outstanding.hint': 'Work still to be done',
  'admin.nav.equipment': 'Equipment',
  'admin.nav.equipment.hint': 'Every item on site',
  'admin.nav.rules': 'Maintenance',
  'admin.nav.rules.hint': 'What gets done, how often',
  'admin.nav.types': 'Types',
  'admin.nav.types.hint': 'Categories of equipment',
  'admin.nav.history': 'History',
  'admin.nav.history.hint': 'Completed work',
  'admin.nav.activity': 'Activity',
  'admin.nav.activity.hint': 'Configuration changes',
  'admin.nav.theme.toLight': 'Switch to light appearance',
  'admin.nav.theme.toDark': 'Switch to dark appearance',
  'admin.nav.theme.toggle': 'Switch appearance',
  'admin.nav.timezone.hint': 'All due dates are calculated in this timezone',
  'admin.nav.role': 'Administrator',
  'admin.nav.closeMenu': 'Close menu',

  /* ----------------------------------- admin/components/primitives.tsx --- */
  'admin.common.panel.open': 'Open',
  'admin.common.taskRow.hidden': 'Hidden — deactivated',
  'admin.common.taskRow.reschedule': 'Reschedule this task',
  'admin.common.completion.noNote': 'No note left',

  /* -------------------------------- admin/components/EquipmentForm.tsx --- */
  'admin.equipmentForm.add': 'Add equipment',
  'admin.equipmentForm.edit': 'Edit equipment',
  'admin.equipmentForm.save': 'Save changes',
  'admin.equipmentForm.subtitle': 'One record per physical item',
  'admin.equipmentForm.code': 'Asset code',
  'admin.equipmentForm.code.placeholder': 'HVAC-06',
  'admin.equipmentForm.code.hint': 'Unique across the estate. It is what workers look for on the label.',
  'admin.equipmentForm.name': 'Name',
  'admin.equipmentForm.name.placeholder': 'Rooftop unit — East wing',
  'admin.equipmentForm.type': 'Equipment type',
  'admin.equipmentForm.type.hint': 'The item inherits every maintenance task defined for this type.',
  'admin.equipmentForm.type.hintChanging': 'Changing the type opens the new type’s schedule. Pending work under rules that no longer apply goes dormant at its own date — nothing is deleted, and moving the item back restores it. History is never touched.',
  'admin.equipmentForm.location': 'Location',
  'admin.equipmentForm.location.placeholder': 'Roof, North wing',
  'admin.equipmentForm.location.hint': 'Optional. Shown to workers so they can find it.',
  'admin.equipmentForm.active.on': 'In service',
  'admin.equipmentForm.active.off': 'Deactivated',
  'admin.equipmentForm.active.onHint': 'Its maintenance appears in the worker app.',
  'admin.equipmentForm.active.offHint': 'Pending tasks are hidden and keep their dates. History is preserved.',
  'admin.equipmentForm.customDue': 'Set the first due date myself',
  'admin.equipmentForm.customDue.onHint': 'Every inherited task will first fall due on the date below.',
  'admin.equipmentForm.customDue.offHint': 'By default each task first falls due one interval from today.',
  'admin.equipmentForm.firstDue': 'First due date',
  'admin.equipmentForm.preview.inherits': { one: 'This item will inherit 1 maintenance task', other: 'This item will inherit {count} maintenance tasks' },
  'admin.equipmentForm.preview.emptyTitle': 'This type has no active maintenance tasks yet',
  'admin.equipmentForm.preview.firstDue': 'first due {date}',
  'admin.equipmentForm.preview.emptyHint': 'You can add maintenance tasks to the type at any time — they will open a schedule on this item automatically.',
  'admin.equipmentForm.toast.updated': 'Equipment updated',
  'admin.equipmentForm.toast.updatedBody': '{code} — {name}',
  'admin.equipmentForm.toast.added': '{code} added',
  'admin.equipmentForm.toast.tasksScheduled': { one: '1 maintenance task scheduled for it.', other: '{count} maintenance tasks scheduled for it.' },
  'admin.equipmentForm.toast.noTasks': 'This type has no maintenance tasks yet.',

  /* ------------------------------------- admin/components/RuleForm.tsx --- */
  'admin.ruleForm.preset.weekly': 'Weekly',
  'admin.ruleForm.preset.fortnightly': 'Fortnightly',
  'admin.ruleForm.preset.monthly': 'Monthly',
  'admin.ruleForm.preset.quarterly': 'Quarterly',
  'admin.ruleForm.preset.twiceAYear': 'Twice a year',
  'admin.ruleForm.preset.yearly': 'Yearly',
  'admin.ruleForm.toast.updated': 'Maintenance task updated',
  'admin.ruleForm.toast.frequencyBody': 'The new frequency applies to the next occurrence. Pending due dates are unchanged.',
  'admin.ruleForm.toast.added': '“{title}” added',
  'admin.ruleForm.toast.scheduled': { one: '1 item of this type now has it scheduled.', other: '{count} items of this type now have it scheduled.' },
  'admin.ruleForm.toast.noEquipment': 'No equipment of this type yet — it will be scheduled as soon as you add some.',
  'admin.ruleForm.saveFailed': 'Could not save. Please try again.',
  'admin.ruleForm.title.edit': 'Edit maintenance task',
  'admin.ruleForm.title.new': 'New maintenance task',
  'admin.ruleForm.subtitle': 'For every {type}',
  'admin.ruleForm.saveChanges': 'Save changes',
  'admin.ruleForm.submit': 'Add maintenance task',
  'admin.ruleForm.appliesTo': 'Applies to',
  'admin.ruleForm.typeOption': { one: '{name} — 1 item', other: '{name} — {count} items' },
  'admin.ruleForm.appliesToHint': 'Every item of this type inherits it, each with its own schedule.',
  'admin.ruleForm.titleField': 'What needs doing',
  'admin.ruleForm.titlePlaceholder': 'Replace air filters',
  'admin.ruleForm.instructions': 'Instructions',
  'admin.ruleForm.instructionsPlaceholder': 'Write it the way you would explain it to someone doing this for the first time.',
  'admin.ruleForm.instructionsHint': 'Shown to the worker on their phone, right above the completion form.',
  'admin.ruleForm.howOften': 'How often',
  'admin.ruleForm.everyPrefix': 'Every',
  'admin.ruleForm.intervalValue': 'Interval value',
  'admin.ruleForm.intervalUnit': 'Interval unit',
  'admin.ruleForm.cadenceEcho': '{cadence} — after each completion the next one falls due one interval from the day the work was actually done.',
  'admin.ruleForm.active': 'Active',
  'admin.ruleForm.deactivated': 'Deactivated',
  'admin.ruleForm.activeHint': 'Appears in the worker app for every item of this type.',
  'admin.ruleForm.deactivatedHint': 'Pending tasks are hidden and keep their dates. History is preserved.',
  'admin.ruleForm.frequencyChange': 'Frequency change',
  'admin.ruleForm.frequencyChangeBody': 'Existing pending tasks keep the due dates they already have. The new interval takes effect from the next occurrence generated after a completion. To move a pending task now, reschedule it explicitly.',
  'admin.ruleForm.customDue': 'Set the first due date myself',
  'admin.ruleForm.customDueOn': 'Every item of this type will first fall due on the date below.',
  'admin.ruleForm.customDueOff': 'By default the first occurrence falls due {date}.',
  'admin.ruleForm.firstDueDate': 'First due date',
  'admin.ruleForm.previewCount': { one: '1 existing item will get this on the schedule', other: '{count} existing items will get this on the schedule' },
  'admin.ruleForm.previewNone': 'No equipment of this type yet',
  'admin.ruleForm.previewBody': 'Each keeps its own independent schedule, first due {date}. No past completions are invented.',
  'admin.ruleForm.previewNoneBody': 'Add equipment of this type and it will pick this up automatically.',

  /* ----------------------------- admin/components/RescheduleDialog.tsx --- */
  'admin.reschedule.title': 'Reschedule this task',
  'admin.reschedule.confirm': 'Move this occurrence',
  'admin.reschedule.currentlyDue': 'Currently due {date}',
  'admin.reschedule.shortcut.today': 'Today',
  'admin.reschedule.shortcut.tomorrow': 'Tomorrow',
  'admin.reschedule.shortcut.week': 'In a week',
  'admin.reschedule.shortcut.month': 'In a month',
  'admin.reschedule.newDate': 'New due date',
  'admin.reschedule.reason': 'Reason',
  'admin.reschedule.reason.placeholder': 'Parts on order, contractor unavailable, site closed…',
  'admin.reschedule.reason.hint': 'Optional — but it is what makes the activity log worth reading later.',
  'admin.reschedule.note': 'This moves only this occurrence, on this one item. Once the work is completed, the following occurrence is still calculated from the day it was actually done.',
  'admin.reschedule.toast.done': 'Task rescheduled',
  'admin.reschedule.toast.doneBody': '{rule} on {equipment} now falls due {date}.',
  'admin.reschedule.toast.noChange': 'Nothing to change',
  'admin.reschedule.toast.noChangeBody': 'That task is already due on this date, or it has just been completed.',
  'admin.reschedule.toast.failed': 'Could not reschedule',

  /* -------------------------------- admin/components/ArchiveDialog.tsx --- */
  'admin.archive.title': 'Archive {name}?',
  'admin.archive.subtitle.equipment': 'This equipment will no longer appear anywhere you configure work.',
  'admin.archive.subtitle.rule': 'This maintenance task will no longer appear anywhere you configure work.',
  'admin.archive.subtitle.type': 'This equipment type will no longer appear anywhere you configure work.',
  'admin.archive.records': { one: '1 completed record stays exactly as it is.', other: '{count} completed records stay exactly as they are.' },
  'admin.archive.recordsWhy': { one: 'It carries its own copy of the details, so archiving cannot change what it says.', other: 'Each one carries its own copy of the details, so archiving cannot change what they say.' },
  'admin.archive.pending': { one: '1 pending task will be hidden.', other: '{count} pending tasks will be hidden.' },
  'admin.archive.pendingKept': { one: 'It is not deleted.', other: 'They are not deleted.' },
  'admin.archive.nothingDeleted': 'Nothing is removed from the database. Archiving is how this system retires something that history still points at.',
  'admin.archive.keep': 'Keep it',
  'admin.archive.confirm': 'Archive',
  'admin.archive.done': '{name} archived',
  'admin.archive.doneBody': 'Its completed history is untouched and still readable.',
  'admin.archive.failed': 'Could not archive',

  /* ------------------------------ admin/components/CompletionSheet.tsx --- */
  'admin.completion.title': 'Completed maintenance',
  'admin.completion.photoAlt': 'Photo submitted for {task} on {equipment}',
  'admin.completion.submittedBy': 'Submitted by {name}',
  'admin.completion.fact.equipmentType': 'Equipment type',
  'admin.completion.fact.scheduledFor': 'Scheduled for',
  'admin.completion.fact.completed': 'Completed',
  'admin.completion.fact.punctuality': 'Punctuality',
  'admin.completion.fact.carriedOutBy': 'Carried out by',
  'admin.completion.fact.frequency': 'Frequency at the time',
  'admin.completion.punctuality.onTheDay': 'On the day it was due',
  'admin.completion.punctuality.early': { one: '1 day early', other: '{count} days early' },
  'admin.completion.punctuality.late': { one: '1 day late', other: '{count} days late' },
  'admin.completion.note': 'Note from the field',
  'admin.completion.noNote': 'No comment was left.',
  'admin.completion.instructions': 'Instructions as they stood at the time',
  'admin.completion.immutable': 'This record is permanent. It keeps the equipment and maintenance details as they were on the day, whatever has changed since.',

  /* ------------------------------------------ admin/screens/SignIn.tsx --- */
  'admin.signIn.lede': 'Sign in to configure equipment, watch the schedule and review completed work.',
  'admin.signIn.email': 'Email',
  'admin.signIn.email.placeholder': 'you@company.com',
  'admin.signIn.password': 'Password',
  'admin.signIn.workerHint': 'Workers sign in to the separate worker app. This one is for administrators only.',
  'admin.signIn.demo': 'Demo administrator —',

  /* --------------------------------------- admin/screens/Dashboard.tsx --- */
  'admin.dashboard.title': 'Overview',
  'admin.dashboard.lede.estate': { one: '1 active item across {types}', other: '{count} active items across {types}' },
  'admin.dashboard.lede.types': { one: '1 type', other: '{count} types' },
  'admin.dashboard.refresh': 'Refresh',
  'admin.dashboard.refreshing': 'Refreshing',
  'admin.dashboard.tile.equipment.label': 'Active equipment',
  'admin.dashboard.tile.equipment.deactivated': { one: '1 item deactivated', other: '{count} items deactivated' },
  'admin.dashboard.tile.equipment.allActive': 'All items in service',
  'admin.dashboard.tile.overdue.oldest': { one: 'Oldest 1 day past due', other: 'Oldest {count} days past due' },
  'admin.dashboard.tile.overdue.none': 'Nothing is late',
  'admin.dashboard.tile.today.scheduled': 'Scheduled for {date}',
  'admin.dashboard.tile.today.none': 'Nothing scheduled today',
  'admin.dashboard.tile.week.label': 'Next seven days',
  'admin.dashboard.tile.week.outstanding': { one: '1 task outstanding in total', other: '{count} tasks outstanding in total' },
  'admin.dashboard.load.title': 'The fortnight ahead',
  'admin.dashboard.load.pressure': { one: '1 task needs attention today or sooner', other: '{count} tasks need attention today or sooner' },
  'admin.dashboard.load.clear': 'Nothing is late — the schedule is clear',
  'admin.dashboard.load.open': 'Open the task list',
  'admin.dashboard.load.empty.title': 'Nothing is scheduled',
  'admin.dashboard.load.empty.body': 'Every item is either deactivated or has no active maintenance task. Add one and a schedule opens here.',
  'admin.dashboard.load.empty.action': 'Add a maintenance task',
  'admin.dashboard.setup.title': 'Nothing set up yet',
  'admin.dashboard.setup.body': 'Start with an equipment type, give it the maintenance it needs, then add the physical items. Each one gets its own schedule.',
  'admin.dashboard.setup.action': 'Create the first type',
  'admin.dashboard.load.scale': 'Tasks falling due each day',
  'admin.dashboard.load.peak': { one: '{count} at the peak', other: '{count} at the peak' },
  'admin.dashboard.load.axisToday': 'Today',
  'admin.dashboard.load.tip': { one: '{weekday} {date}: 1 task', other: '{weekday} {date}: {count} tasks' },
  'admin.dashboard.load.tipCarried': { one: '{date}: 1 due, including {carried} overdue', other: '{date}: {count} due, including {carried} overdue' },
  'admin.dashboard.ontime.title': 'On-time rate',
  'admin.dashboard.ontime.subtitle': 'Completed by the due date, last thirty days',
  'admin.dashboard.ontime.open': 'See history',
  'admin.dashboard.ontime.met': { one: '{onTime} of 1 completion met its due date', other: '{onTime} of {count} completions met their due date' },
  'admin.dashboard.ontime.total': { one: '1 completion recorded in total', other: '{count} completions recorded in total' },
  'admin.dashboard.ontime.spark': '28-day activity',
  'admin.dashboard.attention.title': 'Needs attention',
  'admin.dashboard.attention.subtitle': { one: '1 task past due', other: '{count} tasks past due' },
  'admin.dashboard.attention.none': 'Nothing is overdue',
  'admin.dashboard.attention.open': 'See all overdue',
  'admin.dashboard.attention.empty.title': 'Everything is up to date',
  'admin.dashboard.attention.empty.body': 'No maintenance is past its due date. The next items are scheduled below.',
  'admin.dashboard.recent.title': 'Recently completed',
  'admin.dashboard.recent.subtitle': 'Submitted from the worker app',
  'admin.dashboard.recent.open': 'Full history',
  'admin.dashboard.recent.empty.title': 'No completions yet',
  'admin.dashboard.recent.empty.body': 'Work submitted by the team will appear here, photo and all.',
  'admin.dashboard.types.title': 'Equipment types',
  'admin.dashboard.types.subtitle': { one: '1 type · {tasks}', other: '{count} types · {tasks}' },
  'admin.dashboard.types.tasks': { one: '1 active maintenance task', other: '{count} active maintenance tasks' },
  'admin.dashboard.types.open': 'Manage types',
  'admin.dashboard.next.title': 'Coming up',
  'admin.dashboard.next.subtitle': 'The next scheduled work',
  'admin.dashboard.next.open': 'See the schedule',
  'admin.dashboard.next.empty.title': 'Nothing scheduled',
  'admin.dashboard.next.empty.body': 'Add equipment or a maintenance task to start a schedule.',
  'admin.dashboard.hidden.body': { one: '1 pending task is hidden because its equipment or maintenance task is deactivated. It keeps its due date and reappears the moment you reactivate.', other: '{count} pending tasks are hidden because their equipment or maintenance task is deactivated. They keep their due dates and reappear the moment you reactivate.' },
  'admin.dashboard.hidden.action': 'Show them',

  /* --------------------------------------- admin/screens/TaskBoard.tsx --- */
  'admin.tasks.title': 'Outstanding work',
  'admin.tasks.outstandingCount': { one: '1 task outstanding', other: '{count} tasks outstanding' },
  'admin.tasks.loading': 'Loading the schedule…',
  'admin.tasks.refresh': 'Refresh',
  'admin.tasks.bucket.all': 'Everything',
  'admin.tasks.filter.status': 'Filter by due status',
  'admin.tasks.filter.dueOn': 'Due on {date}',
  'admin.tasks.filter.clearDate': 'Clear the date filter',
  'admin.tasks.search.placeholder': 'Search by asset code, name, location or task',
  'admin.tasks.search.label': 'Search outstanding work',
  'admin.tasks.search.clear': 'Clear search',
  'admin.tasks.filter.type': 'Filter by equipment type',
  'admin.tasks.filter.allTypes': 'All types',
  'admin.tasks.filter.equipment': 'Filter by equipment',
  'admin.tasks.filter.allEquipment': 'All equipment',
  'admin.tasks.includeHidden': 'Include hidden',
  'admin.tasks.empty.title': 'No outstanding work',
  'admin.tasks.empty.body': 'Every scheduled task has been completed. New occurrences appear as they fall due.',
  'admin.tasks.empty.filtered': 'Nothing matches those filters',
  'admin.tasks.empty.filteredBody': 'Try widening the search, or clear the filters to see the whole schedule.',
  'admin.tasks.empty.clearFilters': 'Clear filters',
  'admin.tasks.truncated': 'Showing the {shown} most urgent of {total} outstanding tasks — the counts above cover all of them. Filter by type or equipment, or search, to reach the rest.',

  /* ----------------------------------- admin/screens/EquipmentList.tsx --- */
  'admin.equipment.title': 'Equipment',
  'admin.equipment.lede.count': { one: '{count} item shown · one record per physical thing on site', other: '{count} items shown · one record per physical thing on site' },
  'admin.equipment.lede.loading': 'Loading the estate…',
  'admin.equipment.add': 'Add equipment',
  'admin.equipment.filter.scope': 'Filter by status',
  'admin.equipment.scope.active': 'In service',
  'admin.equipment.scope.inactive': 'Deactivated',
  'admin.equipment.scope.all': 'Everything',
  'admin.equipment.search.placeholder': 'Search by code, name or location',
  'admin.equipment.search.aria': 'Search equipment',
  'admin.equipment.search.clear': 'Clear search',
  'admin.equipment.filter.type': 'Filter by type',
  'admin.equipment.filter.allTypes': 'All types',
  'admin.equipment.filter.typeOption': '{name} ({count})',
  'admin.equipment.empty.title': 'No equipment yet',
  'admin.equipment.empty.body': 'Add your first item and it will inherit every maintenance task defined for its type.',
  'admin.equipment.empty.filtered.title': 'Nothing matches',
  'admin.equipment.empty.filtered.body': 'Try a different search, or clear the type filter.',
  'admin.equipment.card.deactivated': 'Deactivated',
  'admin.equipment.card.noLocation': 'No location recorded',
  'admin.equipment.card.scheduled': { one: 'scheduled', other: 'scheduled' },
  'admin.equipment.card.completed': { one: 'completed', other: 'completed' },
  'admin.equipment.card.next': 'Next {date}',
  'admin.equipment.card.noSchedule': 'No schedule',
  'admin.equipment.card.lastServiced': 'Last serviced {when}',
  'admin.equipment.card.neverServiced': 'Never serviced',

  /* --------------------------------- admin/screens/EquipmentDetail.tsx --- */
  'admin.equipmentDetail.backToEquipment': 'Equipment',
  'admin.equipmentDetail.flag.deactivated': 'Deactivated',
  'admin.equipmentDetail.rule.deactivatedFlag': 'Deactivated',
  'admin.equipmentDetail.noLocation': 'No location recorded',
  'admin.equipmentDetail.lastServiced': 'Last serviced {when}',
  'admin.equipmentDetail.neverServiced': 'Never serviced',
  'admin.equipmentDetail.stat.scheduled': 'Scheduled',
  'admin.equipmentDetail.stat.completed': 'Completed',
  'admin.equipmentDetail.stat.nextDue': 'Next due',
  'admin.equipmentDetail.action.edit': 'Edit',
  'admin.equipmentDetail.action.duplicate': 'Duplicate',
  'admin.equipmentDetail.action.deactivate': 'Deactivate',
  'admin.equipmentDetail.action.reactivate': 'Reactivate',
  'admin.equipmentDetail.action.archive': 'Archive',
  'admin.equipmentDetail.tabs.aria': 'Equipment detail sections',
  'admin.equipmentDetail.tab.schedule': 'Schedule',
  'admin.equipmentDetail.tab.history': 'History',
  'admin.equipmentDetail.tab.activity': 'Activity',
  'admin.equipmentDetail.reactivated': 'Back in service',
  'admin.equipmentDetail.reactivatedBody': 'Its pending tasks are visible again, at their existing due dates.',
  'admin.equipmentDetail.deactivated': 'Deactivated',
  'admin.equipmentDetail.deactivatedBody': 'Pending tasks are hidden and keep their dates. Completed history is untouched.',
  'admin.equipmentDetail.updateFailed': 'Could not update',
  'admin.equipmentDetail.empty.scheduleTitle': 'No maintenance scheduled',
  'admin.equipmentDetail.empty.scheduleBody': 'Add a maintenance task to this equipment type and a schedule opens here automatically.',
  'admin.equipmentDetail.empty.addTask': 'Add a maintenance task',
  'admin.equipmentDetail.empty.hiddenTitle': 'Schedule hidden while deactivated',
  'admin.equipmentDetail.empty.hiddenBody': 'Its pending tasks still exist and keep their due dates. Reactivate the item to bring them back.',
  'admin.equipmentDetail.empty.historyTitle': 'No completed work yet',
  'admin.equipmentDetail.empty.historyBody': 'Completions submitted from the worker app appear here, with the photo, the person and the exact time.',
  'admin.equipmentDetail.empty.activityTitle': 'No changes recorded',
  'admin.equipmentDetail.empty.activityBody': 'Configuration changes and reschedules for this item will be listed here.',
  'admin.equipmentDetail.hiddenNote': { one: '1 pending task is hidden because the maintenance task or the equipment is deactivated. Dates are preserved.', other: '{count} pending tasks are hidden because the maintenance task or the equipment is deactivated. Dates are preserved.' },
  'admin.equipmentDetail.inheritedFrom': 'Inherited from {type}',
  'admin.equipmentDetail.duplicated': { one: '{code} created', other: '{count} new items created' },
  'admin.equipmentDetail.duplicatedBody': 'Each has a new identifier and a fresh schedule. No history was copied.',
  'admin.equipmentDetail.duplicate.title': 'Duplicate this equipment',
  'admin.equipmentDetail.duplicate.subtitle': 'Based on {code}',
  'admin.equipmentDetail.duplicate.note': 'A duplicate is a new physical item: it gets its own asset code and a schedule that starts fresh today. Completion history is never copied — that belongs to the original.',
  'admin.equipmentDetail.duplicate.codeLabel': 'Asset code',
  'admin.equipmentDetail.duplicate.hintOne': 'Leave blank to append -COPY to the original code.',
  'admin.equipmentDetail.duplicate.hintMany': 'A two-digit suffix is added to each copy.',
  'admin.equipmentDetail.duplicate.countLabel': 'How many',
  'admin.equipmentDetail.duplicate.firstDue': 'First occurrence for each copy falls due one interval from {date}.',
  'admin.equipmentDetail.duplicate.submit': { one: 'Create a copy', other: 'Create {count} copies' },
  'admin.equipmentDetail.duplicate.failed': 'Could not duplicate',

  /* ---------------------------------------- admin/screens/RuleList.tsx --- */
  'admin.rules.title': 'Maintenance',
  'admin.rules.lede': { one: '1 task across {types} · each item of a type keeps its own schedule', other: '{count} tasks across {types} · each item of a type keeps its own schedule' },
  'admin.rules.lede.types': { one: '1 equipment type', other: '{count} equipment types' },
  'admin.rules.add': 'New maintenance task',
  'admin.rules.filter.scope': 'Filter by status',
  'admin.rules.scope.all': 'Everything',
  'admin.rules.scope.active': 'Active',
  'admin.rules.scope.inactive': 'Deactivated',
  'admin.rules.filter.type': 'Filter by type',
  'admin.rules.filter.allTypes': 'All equipment types',
  'admin.rules.filter.typeOption': '{name} ({count})',
  'admin.rules.empty.filtered.title': 'Nothing matches',
  'admin.rules.empty.filtered.body': 'Try clearing the filters.',
  'admin.rules.empty.title': 'No maintenance tasks yet',
  'admin.rules.empty.body': 'Define what needs doing and how often. Every item of the chosen type picks it up straight away.',
  'admin.rules.group.count': { one: '1 task', other: '{count} tasks' },
  'admin.rules.group.add': 'Add',
  'admin.rules.card.deactivated': 'Deactivated',
  'admin.rules.card.noInstructions': 'No instructions written yet.',
  'admin.rules.card.scheduled': { one: '1 scheduled', other: '{count} scheduled' },
  'admin.rules.card.completions': { one: '1 completion', other: '{count} completions' },

  /* -------------------------------------- admin/screens/RuleDetail.tsx --- */
  'admin.ruleDetail.backToRules': 'Maintenance',
  'admin.ruleDetail.reactivated': 'Reactivated',
  'admin.ruleDetail.reactivatedBody': 'Pending tasks are visible again at their existing due dates, overdue ones included.',
  'admin.ruleDetail.deactivated': 'Deactivated',
  'admin.ruleDetail.deactivatedBody': 'Pending tasks are hidden and keep their dates. Completed history is untouched.',
  'admin.ruleDetail.updateFailed': 'Could not update',
  'admin.ruleDetail.flag.deactivated': 'Deactivated',
  'admin.ruleDetail.noInstructions': 'No instructions written yet — workers see only the title.',
  'admin.ruleDetail.stat.scheduled': 'Scheduled',
  'admin.ruleDetail.stat.completed': 'Completed',
  'admin.ruleDetail.action.edit': 'Edit',
  'admin.ruleDetail.action.deactivate': 'Deactivate',
  'admin.ruleDetail.action.reactivate': 'Reactivate',
  'admin.ruleDetail.action.archive': 'Archive',
  'admin.ruleDetail.tabs.aria': 'Sections',
  'admin.ruleDetail.tab.schedule': 'Schedule',
  'admin.ruleDetail.tab.history': 'History',
  'admin.ruleDetail.tab.activity': 'Activity',
  'admin.ruleDetail.empty.scheduleTitle': 'No equipment of this type yet',
  'admin.ruleDetail.empty.scheduleBody': 'Add equipment of this type and it will inherit this task with its own schedule.',
  'admin.ruleDetail.empty.hiddenTitle': 'Schedules hidden while deactivated',
  'admin.ruleDetail.empty.hiddenBody': 'Every pending occurrence still exists and keeps its date. Reactivate to bring them back.',
  'admin.ruleDetail.empty.seeEquipment': 'See equipment',
  'admin.ruleDetail.hiddenNote': { one: '1 occurrence is hidden because its equipment is deactivated. Dates are preserved.', other: '{count} occurrences are hidden because their equipment is deactivated. Dates are preserved.' },
  'admin.ruleDetail.empty.historyTitle': 'Not completed yet',
  'admin.ruleDetail.empty.historyBody': 'Once this maintenance is carried out, every completion appears here with its photo.',
  'admin.ruleDetail.empty.activityTitle': 'No changes recorded',

  /* ---------------------------------------- admin/screens/TypeList.tsx --- */
  'admin.types.title': 'Equipment types',
  'admin.types.lede': 'Define maintenance once per type. Every item of that type inherits it with a schedule of its own.',
  'admin.types.add': 'New type',
  'admin.types.empty.title': 'No equipment types yet',
  'admin.types.empty.body': 'Start with a type — “HVAC Unit”, “Forklift”, “Fire Extinguisher” — then define what maintenance it needs.',
  'admin.types.toast.archived': 'Type archived',
  'admin.types.toast.archivedBody': 'Its history is preserved and stays readable.',
  'admin.types.toast.archiveFailed': 'Could not archive',
  'admin.types.card.edit': 'Edit {name}',
  'admin.types.card.inService': { one: 'in service', other: 'in service' },
  'admin.types.card.equipmentDeactivated': { one: '{count} deactivated', other: '{count} deactivated' },
  'admin.types.card.tasks': { one: 'maintenance task', other: 'maintenance tasks' },
  'admin.types.card.tasksDeactivated': { one: '{count} deactivated', other: '{count} deactivated' },
  'admin.types.card.equipmentLink': 'Equipment',
  'admin.types.card.maintenanceLink': 'Maintenance',
  'admin.types.toast.updated': 'Type updated',
  'admin.types.toast.added': '“{name}” added',
  'admin.types.toast.addedBody': 'Now define what maintenance it needs.',
  'admin.types.form.saveFailed': 'Could not save. Please try again.',
  'admin.types.form.editTitle': 'Edit equipment type',
  'admin.types.form.newTitle': 'New equipment type',
  'admin.types.form.archive': 'Archive',
  'admin.types.form.save': 'Save changes',
  'admin.types.form.create': 'Create type',
  'admin.types.form.name': 'Name',
  'admin.types.form.namePlaceholder': 'HVAC Unit',
  'admin.types.form.colour': 'Colour',
  'admin.types.form.symbol': 'Symbol',
  'admin.types.form.archiveNote': 'Archiving hides a type and its maintenance tasks. It is only possible once no equipment uses it. Completed history always survives — it carries its own copy of the details.',
  'admin.types.accent.aurora': 'Aurora',
  'admin.types.accent.ice': 'Ice',
  'admin.types.accent.cobalt': 'Cobalt',
  'admin.types.accent.orchid': 'Orchid',
  'admin.types.accent.ember': 'Ember',
  'admin.types.accent.sunset': 'Sunset',
  'admin.types.accent.gold': 'Gold',
  'admin.types.accent.lime': 'Lime',
  'admin.types.symbol.cube': 'Cube',
  'admin.types.symbol.fan': 'Fan',
  'admin.types.symbol.bolt': 'Lightning bolt',
  'admin.types.symbol.drop': 'Droplet',
  'admin.types.symbol.gear': 'Gear',
  'admin.types.symbol.flame': 'Flame',
  'admin.types.symbol.wave': 'Wave',
  'admin.types.symbol.shield': 'Shield',
  'admin.types.symbol.truck': 'Truck',
  'admin.types.symbol.leaf': 'Leaf',
  'admin.types.symbol.chip': 'Chip',
  'admin.types.symbol.lift': 'Lift',

  /* ----------------------------------- admin/screens/HistoryScreen.tsx --- */
  'admin.history.title': 'Completion history',
  'admin.history.lede.filtered': { one: '{count} completed job matching your filters · every one with its photo', other: '{count} completed jobs matching your filters · every one with its photo' },
  'admin.history.lede.all': { one: '{count} completed job recorded · every one with its photo', other: '{count} completed jobs recorded · every one with its photo' },
  'admin.history.search.placeholder': 'Search by equipment, task, person or comment',
  'admin.history.search.aria': 'Search history',
  'admin.history.search.clear': 'Clear search',
  'admin.history.filter.type': 'Filter by type',
  'admin.history.filter.allTypes': 'All types',
  'admin.history.filter.person': 'Filter by person',
  'admin.history.filter.anyone': 'Anyone',
  'admin.history.filter.fromDate': 'From date',
  'admin.history.filter.toDate': 'To date',
  'admin.history.filter.rangeTo': 'to',
  'admin.history.range.last7': 'Last 7 days',
  'admin.history.range.last30': 'Last 30 days',
  'admin.history.empty.filtered.title': 'Nothing matches those filters',
  'admin.history.empty.filtered.body': 'Try a wider date range, or clear the filters.',
  'admin.history.empty.title': 'No completed work yet',
  'admin.history.empty.body': 'When the team submits maintenance from the worker app, it lands here — photo, person, and the exact time it was recorded.',
  'admin.history.empty.clearFilters': 'Clear filters',
  'admin.history.empty.seeTasks': 'See outstanding work',
  'admin.history.showMore': { one: 'Show 1 more', other: 'Show {count} more' },
  'admin.history.more.shown': 'Showing {shown} of {total}',
  'admin.history.more.shownRange': 'Showing {shown} of {total} · {from} to {to}',
  'admin.history.more.shownFrom': 'Showing {shown} of {total} · from {from}',
  'admin.history.more.shownTo': 'Showing {shown} of {total} · up to {to}',
  'admin.history.end': { one: 'That is all {count} record.', other: 'That is all {count} records.' },

  /* ---------------------------------- admin/screens/ActivityScreen.tsx --- */
  'admin.activity.title': 'Activity',
  'admin.activity.lede': 'Every configuration change and every reschedule, with who did it and when.',
  'admin.activity.filter.aria': 'Filter activity',
  'admin.activity.scope.all': 'Everything',
  'admin.activity.scope.schedule': 'Reschedules',
  'admin.activity.scope.config': 'Configuration',
  'admin.activity.empty.title': 'Nothing recorded yet',
  'admin.activity.empty.body': 'Changes to equipment, types, maintenance tasks and schedules will be listed here.',
  'admin.activity.detail.reason': '“{reason}”',

  /* ----------------------------------------- worker/screens/SignIn.tsx --- */
  'worker.signIn.lede': 'Sign in to see what needs doing today.',
  'worker.signIn.email': 'Email',
  'worker.signIn.email.placeholder': 'you@company.com',
  'worker.signIn.password': 'Password',
  'worker.signIn.demo': 'Demo —',

  /* --------------------------------------- worker/screens/TaskList.tsx --- */
  'worker.list.greeting.morning': 'Morning, {name}',
  'worker.list.greeting.afternoon': 'Afternoon, {name}',
  'worker.list.greeting.evening': 'Evening, {name}',
  'worker.list.title.clear': 'Nothing due yet',
  'worker.list.title.toDo': { one: '1 to do', other: '{count} to do' },
  'worker.list.refresh': 'Refresh the list',
  'worker.list.toggleTheme': 'Switch appearance',
  'worker.list.searchPlaceholder': 'Asset code, name or location',
  'worker.list.searchLabel': 'Search tasks',
  'worker.list.empty.noMatchTitle': 'Nothing matches',
  'worker.list.empty.noMatchBody': 'Try a different asset code or location.',
  'worker.list.empty.clearTitle': 'All clear',
  'worker.list.empty.clearBody': 'Every scheduled job has been done. New ones appear here as they fall due.',
  'worker.list.clearSearch': 'Clear search',
  'worker.list.show': 'Show',
  'worker.list.hide': 'Hide',
  'worker.list.truncated': { one: 'Showing the most urgent {shown} of 1 job. Search to find a specific one.', other: 'Showing the most urgent {shown} of {count} jobs. Search to find a specific one.' },
  'worker.list.footer': { one: '1 job outstanding · times shown in {zone}', other: '{count} jobs outstanding · times shown in {zone}' },

  /* ------------------------------------- worker/screens/TaskDetail.tsx --- */
  'worker.detail.allJobs': 'All jobs',
  'worker.detail.gone': 'This job is no longer outstanding.',
  'worker.detail.goneDetail': 'Somebody may have completed it, or it may have been deactivated.',
  'worker.detail.backToList': 'Back to the list',
  'worker.detail.sessionEnded': 'Your session has ended. Sign in again and the job will still be here.',
  'worker.detail.stillOpen': 'Something went wrong. The job is still open — try again.',
  'worker.detail.toast.alreadyDone': 'Already done',
  'worker.detail.toast.alreadyDoneBody': 'Someone else submitted this one. Here is the up-to-date list.',
  'worker.detail.where': 'Where',
  'worker.detail.noLocation': 'No location recorded',
  'worker.detail.due': 'Due',
  'worker.detail.instructions': 'What to do',
  'worker.detail.finish': 'Finish the job',
  'worker.detail.check': 'Maintenance completed',
  'worker.detail.photoHint': 'One photo showing the work. It is stored with the record and only administrators can see it.',
  'worker.detail.comment': 'Anything to add?',
  'worker.detail.comment.placeholder': 'Optional — parts used, something you noticed, anything worth knowing next time.',
  'worker.detail.missing.tick': 'Tick “Maintenance completed” first',
  'worker.detail.missing.photo': 'Add one photo of the work',
  'worker.detail.submitting': 'Submitting…',
  'worker.detail.submit': 'Submit completion',
  'worker.detail.submit.progress': { one: 'Submit — {count} of 2 ready', other: 'Submit — {count} of 2 ready' },

  /* ------------------------------ worker/components/SuccessOverlay.tsx --- */
  'worker.success.title': 'Logged. Nice one.',
  'worker.success.next': 'Next time: {date}',
  'worker.success.inDays': { one: 'in 1 day', other: 'in {count} days' },
  'worker.success.backToList': 'Back to the list',
} satisfies Record<string, string | { one: string; other: string }>;
