import type { Dictionary } from '../i18n';

/**
 * Français.
 *
 * Vouvoiement throughout — this is a workplace tool, and «tu» would be wrong
 * in a maintenance log a supervisor also reads. French typography is followed
 * where it matters on screen: a narrow space before «:» and «%», «’» rather
 * than a straight apostrophe.
 *
 * Typed as `Dictionary`, so a key missing from here is a build error.
 */
export const fr: Dictionary = {
  /* --------------------------------------------------------- common --- */
  'common.loading': 'Chargement…',
  'common.retry': 'Réessayer',
  'common.cancel': 'Annuler',
  'common.save': 'Enregistrer',
  'common.close': 'Fermer',
  'common.clear': 'Effacer',
  'common.search': 'Rechercher',
  'common.back': 'Retour',
  'common.signOut': 'Se déconnecter',
  'common.signIn': 'Se connecter',
  'common.optional': 'Facultatif',
  'common.none': 'Aucun',
  'common.appearance': 'Apparence',
  'common.language': 'Langue',
  'common.somethingWrong': 'Une erreur est survenue. Veuillez réessayer.',
  'common.offline': 'Serveur injoignable. Veuillez réessayer.',

  /* -------------------------------------------------------- settings --- */
  'theme.dark': 'Sombre',
  'theme.light': 'Clair',
  'theme.system': 'Système',
  'lang.choose': 'Choisir la langue',
  'lang.changed': 'Langue modifiée',
  'lang.changedBody': 'L’interface est maintenant en français.',

  /* ---------------------------------------------------------- status --- */
  'status.overdue': 'En retard',
  'status.overdue.short': 'En retard',
  'status.today': 'Pour aujourd’hui',
  'status.today.short': 'Aujourd’hui',
  'status.soon': 'Cette semaine',
  'status.soon.short': 'Cette semaine',
  'status.later': 'Planifié',
  'status.later.short': 'Plus tard',

  /* ------------------------------------------------------------- due --- */
  'due.overdue': { one: '{count} jour de retard', other: '{count} jours de retard' },
  'due.today': 'Pour aujourd’hui',
  'due.tomorrow': 'Pour demain',
  'due.inDays': { one: 'Dans {count} jour', other: 'Dans {count} jours' },
  'due.overdueShort': { one: '{count} j de retard', other: '{count} j de retard' },
  'due.earlyShort': { one: '{count} j d’avance', other: '{count} j d’avance' },
  'due.onTheDay': 'Le jour même',

  /* --------------------------------------------------------- urgency --- */
  'urgency.overdue': { one: '{count} en retard', other: '{count} en retard' },
  'urgency.today': { one: '{count} pour aujourd’hui', other: '{count} pour aujourd’hui' },
  'urgency.soon': { one: '{count} cette semaine', other: '{count} cette semaine' },
  'urgency.clear': 'Rien ne demande votre attention',
  'urgency.notLate': 'Aucun retard — {list}',
  'urgency.and': '{list} et {last}',

  /* ------------------------------------------------ shared components --- */
  'ui.field.optional': 'Facultatif',
  'ui.field.required': 'Obligatoire',
  'ui.photo.take': 'Prendre une photo',
  'ui.photo.choose': 'Choisir une photo',
  'ui.photo.retake': 'Remplacer la photo',
  'ui.photo.uploading': 'Envoi en cours…',
  'ui.photo.failed': 'La photo n’a pas pu être envoyée. Réessayez.',
  'ui.photo.tooBig': 'Cette image est trop volumineuse. Reprenez une photo et réessayez.',
  'ui.photo.wrongType': 'Ce fichier n’est pas une image. Une photo du travail est obligatoire.',
  'ui.photo.attached': 'Photo jointe',
  'ui.photo.remove': 'Retirer la photo',
  'ui.state.emptyTitle': 'Rien pour le moment',
  'ui.state.errorTitle': 'Une erreur est survenue',
  'ui.pull.release': 'Relâchez pour actualiser',
  'ui.pull.refreshing': 'Actualisation…',

  /* ------------------------------------------- errors, by server code --- */
  'error.UNAUTHORIZED': 'Votre session a expiré. Veuillez vous reconnecter.',
  'error.FORBIDDEN': 'Vous n’avez pas l’autorisation de faire cela.',
  'error.NOT_FOUND': 'Cet élément n’existe plus.',
  'error.ALREADY_COMPLETED': 'Déjà terminée — quelqu’un vous a devancé.',
  'error.EQUIPMENT_INACTIVE': 'Cet équipement a été désactivé. Rien à envoyer.',
  'error.RULE_INACTIVE': 'Cette maintenance a été désactivée. Rien à envoyer.',
  'error.RULE_NOT_APPLICABLE': 'Cette maintenance ne s’applique plus à cet équipement. Rien à envoyer.',
  'error.PHOTO_REQUIRED': 'Une photo du travail terminé est obligatoire.',
  'error.PHOTO_REUSED': 'Cette photo est déjà associée à une autre intervention.',
  'error.DUPLICATE_CODE': 'Ce code d’actif est déjà utilisé.',
  'error.DUPLICATE_NAME': 'Ce nom est déjà utilisé.',
  'error.TYPE_IN_USE': 'Ce type comporte encore des équipements.',
  'error.CONFIRMATION_REQUIRED': 'Veuillez confirmer avant de continuer.',
  'error.TOO_MANY_ATTEMPTS': 'Trop de tentatives. Patientez un instant et réessayez.',
  'error.PAYLOAD_TOO_LARGE': 'Ce fichier est trop volumineux.',
  'error.BAD_UPLOAD': 'L’envoi n’a pas pu être lu. Veuillez réessayer.',
  'error.BAD_JSON': 'La requête n’a pas pu être lue. Veuillez réessayer.',
  'error.VALIDATION': 'Veuillez vérifier le champ signalé.',
  'error.INTERNAL': 'Une erreur est survenue sur le serveur. Veuillez réessayer.',
  'error.SIGN_IN': 'Cet e-mail et ce mot de passe ne correspondent à aucun compte.',

  /* ------------------------------- field, unit and role names --- */
  'field.typeName': 'Nom du type',
  'field.assetCode': 'Code d’actif',
  'field.equipmentName': 'Nom de l’équipement',
  'field.equipmentType': 'Type d’équipement',
  'field.taskTitle': 'Intitulé de la maintenance',
  'unit.days': 'jours',
  'unit.weeks': 'semaines',
  'unit.months': 'mois',
  'unit.years': 'ans',
  'role.admin': 'administrateur',
  'role.worker': 'technicien',

  /* ----------------------- messages the server sends, by key --- */
  'server.required': '{field} est obligatoire.',
  'server.tooLong': '{field} ne peut pas dépasser {max} caractères.',
  'server.typeNameTaken': 'Un type d’équipement nommé « {name} » existe déjà.',
  'server.typeGone': 'Ce type d’équipement n’existe plus.',
  'server.typeInUse': {
    one: '{count} équipement utilise encore ce type. Déplacez-le ou archivez-le d’abord.',
    other: '{count} équipements utilisent encore ce type. Déplacez-les ou archivez-les d’abord.',
  },
  'server.badFirstDue': 'La première échéance doit être une date valide.',
  'server.pickRealType': 'Choisissez un type d’équipement qui existe encore.',
  'server.pickRealDate': 'Choisissez une date valide.',
  'server.codeTaken': 'Le code d’actif « {code} » est déjà utilisé.',
  'server.equipmentGone': 'Cet équipement n’existe plus.',
  'server.intervalWhole': 'L’intervalle doit être un nombre entier supérieur à zéro.',
  'server.intervalUnit': 'L’unité de l’intervalle doit être jours, semaines, mois ou ans.',
  'server.intervalCapped': 'Les intervalles sont plafonnés à environ cinquante ans, soit {max} en {unit}.',
  'server.ruleGone': 'Cette maintenance n’existe plus.',
  'server.taskGone': 'Cette tâche n’existe plus.',
  'server.taskNotOutstanding': 'Cette tâche n’est plus en attente.',
  'server.completionGone': 'Cet enregistrement n’existe plus.',
  'server.alreadyCompleted': 'Déjà terminée — quelqu’un vous a devancé.',
  'server.equipmentDeactivated': '{name} a été désactivé. Rien à envoyer.',
  'server.ruleDeactivated': '« {title} » a été désactivée. Rien à envoyer.',
  'server.ruleNotApplicable': '{name} n’est plus un équipement « {title} ». Rien à envoyer.',
  'server.photoRequired': 'Une photo du travail terminé est obligatoire.',
  'server.photoMissing': 'Cette photo est introuvable. Veuillez la joindre à nouveau.',
  'server.photoNotYours': 'Cette photo a été envoyée par quelqu’un d’autre.',
  'server.photoReused': 'Cette photo est déjà associée à une autre intervention.',
  'server.photoUnavailable': 'Cette photo n’est pas disponible.',
  'server.photoOtherCompletion': 'Cette photo appartient à une autre intervention.',
  'server.noPhotoAttached': 'Aucune photo n’a été jointe.',
  'server.badUpload': 'L’envoi n’a pas pu être lu. Veuillez joindre la photo à nouveau.',
  'server.adminOnly': 'Cette action est réservée aux administrateurs.',
  'server.roleOnly': 'Cette action est réservée aux {role}s.',
  'server.wrongApp': 'Ceci est l’application d’administration. Utilisez l’application de terrain pour vous connecter.',
  'server.tickConfirm': 'Cochez « Maintenance terminée » avant d’envoyer.',
  'server.addOnePhoto': 'Joignez une photo du travail terminé.',
  'server.signInToContinue': 'Connectez-vous pour continuer.',
  'server.noAccess': 'Vous n’avez pas accès à cette action.',
  'server.notFound': 'Cet élément n’existe plus.',


  /* ------------------------------------ the worker account sheet --- */
  'worker.account.title': 'Votre compte',
  'worker.account.open': 'Compte, langue et apparence',


  /* ------------------------------------ ui/components/PhotoCapture.tsx --- */
  'ui.photo.defaultLabel': 'Photo du travail effectué',
  'ui.photo.previewAlt': 'La photo que vous allez envoyer',

  /* ----------------------------------------- ui/components/Toaster.tsx --- */
  'ui.toast.dismiss': 'Fermer',

  /* ------------------------------------------ ui/components/charts.tsx --- */
  'ui.chart.valueTooltip': '{label} : {value}',

  /* --------------------------------------- admin/components/Chrome.tsx --- */
  'admin.nav.sections': 'Sections',
  'admin.nav.overview': 'Aperçu',
  'admin.nav.overview.hint': 'Tout en un coup d’œil',
  'admin.nav.outstanding': 'En attente',
  'admin.nav.outstanding.hint': 'Le travail qui reste à faire',
  'admin.nav.equipment': 'Équipements',
  'admin.nav.equipment.hint': 'Tous les équipements du site',
  'admin.nav.rules': 'Maintenance',
  'admin.nav.rules.hint': 'Ce qui est fait, et à quelle fréquence',
  'admin.nav.types': 'Types',
  'admin.nav.types.hint': 'Catégories d’équipements',
  'admin.nav.history': 'Historique',
  'admin.nav.history.hint': 'Travaux terminés',
  'admin.nav.activity': 'Activité',
  'admin.nav.activity.hint': 'Modifications de configuration',
  'admin.nav.theme.toLight': 'Passer à l’apparence claire',
  'admin.nav.theme.toDark': 'Passer à l’apparence sombre',
  'admin.nav.theme.toggle': 'Changer d’apparence',
  'admin.nav.timezone.hint': 'Toutes les échéances sont calculées dans ce fuseau horaire',
  'admin.nav.role': 'Administrateur',
  'admin.nav.closeMenu': 'Fermer le menu',

  /* ----------------------------------- admin/components/primitives.tsx --- */
  'admin.common.panel.open': 'Ouvrir',
  'admin.common.taskRow.hidden': 'Masquée — désactivée',
  'admin.common.taskRow.reschedule': 'Replanifier cette tâche',
  'admin.common.completion.noNote': 'Aucune note',

  /* -------------------------------- admin/components/EquipmentForm.tsx --- */
  'admin.equipmentForm.add': 'Ajouter un équipement',
  'admin.equipmentForm.edit': 'Modifier l’équipement',
  'admin.equipmentForm.save': 'Enregistrer',
  'admin.equipmentForm.subtitle': 'Une fiche par équipement physique',
  'admin.equipmentForm.code': 'Code d’actif',
  'admin.equipmentForm.code.placeholder': 'HVAC-06',
  'admin.equipmentForm.code.hint': 'Unique dans tout le parc. C’est ce que les techniciens cherchent sur l’étiquette.',
  'admin.equipmentForm.name': 'Nom',
  'admin.equipmentForm.name.placeholder': 'Unité de toiture — aile est',
  'admin.equipmentForm.type': 'Type d’équipement',
  'admin.equipmentForm.type.hint': 'L’équipement hérite de toutes les tâches de maintenance définies pour ce type.',
  'admin.equipmentForm.type.hintChanging': 'Changer le type ouvre le planning du nouveau type. Les tâches en attente rattachées à des maintenances qui ne s’appliquent plus passent en sommeil, en conservant leur date — rien n’est supprimé, et il suffit de remettre l’équipement dans son type d’origine pour les rétablir. L’historique n’est jamais modifié.',
  'admin.equipmentForm.location': 'Emplacement',
  'admin.equipmentForm.location.placeholder': 'Toiture, aile nord',
  'admin.equipmentForm.location.hint': 'Facultatif. Visible par les techniciens pour qu’ils trouvent l’équipement.',
  'admin.equipmentForm.active.on': 'En service',
  'admin.equipmentForm.active.off': 'Désactivé',
  'admin.equipmentForm.active.onHint': 'Ses maintenances apparaissent dans l’application des techniciens.',
  'admin.equipmentForm.active.offHint': 'Les tâches en attente sont masquées et gardent leurs dates. L’historique est conservé.',
  'admin.equipmentForm.customDue': 'Définir moi-même la première échéance',
  'admin.equipmentForm.customDue.onHint': 'Toutes les tâches héritées auront pour première échéance la date ci-dessous.',
  'admin.equipmentForm.customDue.offHint': 'Par défaut, la première échéance de chaque tâche tombe un intervalle après la date du jour.',
  'admin.equipmentForm.firstDue': 'Première échéance',
  'admin.equipmentForm.preview.inherits': { one: 'Cet équipement héritera de {count} maintenance', other: 'Cet équipement héritera de {count} maintenances' },
  'admin.equipmentForm.preview.emptyTitle': 'Ce type n’a encore aucune maintenance active',
  'admin.equipmentForm.preview.firstDue': '1re échéance le {date}',
  'admin.equipmentForm.preview.emptyHint': 'Vous pouvez ajouter des maintenances à ce type à tout moment — elles ouvriront automatiquement un planning sur cet équipement.',
  'admin.equipmentForm.toast.updated': 'Équipement mis à jour',
  'admin.equipmentForm.toast.updatedBody': '{code} — {name}',
  'admin.equipmentForm.toast.added': '{code} ajouté',
  'admin.equipmentForm.toast.tasksScheduled': { one: '{count} maintenance planifiée pour cet équipement.', other: '{count} maintenances planifiées pour cet équipement.' },
  'admin.equipmentForm.toast.noTasks': 'Ce type n’a encore aucune maintenance.',

  /* ------------------------------------- admin/components/RuleForm.tsx --- */
  'admin.ruleForm.preset.weekly': 'Hebdomadaire',
  'admin.ruleForm.preset.fortnightly': 'Tous les 15 jours',
  'admin.ruleForm.preset.monthly': 'Mensuel',
  'admin.ruleForm.preset.quarterly': 'Trimestriel',
  'admin.ruleForm.preset.twiceAYear': 'Semestriel',
  'admin.ruleForm.preset.yearly': 'Annuel',
  'admin.ruleForm.toast.updated': 'Maintenance mise à jour',
  'admin.ruleForm.toast.frequencyBody': 'La nouvelle fréquence s’applique à la prochaine occurrence. Les échéances en attente restent inchangées.',
  'admin.ruleForm.toast.added': '« {title} » ajoutée',
  'admin.ruleForm.toast.scheduled': { one: 'Elle est désormais planifiée sur {count} équipement de ce type.', other: 'Elle est désormais planifiée sur {count} équipements de ce type.' },
  'admin.ruleForm.toast.noEquipment': 'Aucun équipement de ce type pour l’instant — elle sera planifiée dès que vous en ajouterez un.',
  'admin.ruleForm.saveFailed': 'Enregistrement impossible. Veuillez réessayer.',
  'admin.ruleForm.title.edit': 'Modifier la maintenance',
  'admin.ruleForm.title.new': 'Nouvelle maintenance',
  'admin.ruleForm.subtitle': 'Pour chaque {type}',
  'admin.ruleForm.saveChanges': 'Enregistrer les modifications',
  'admin.ruleForm.submit': 'Ajouter une maintenance',
  'admin.ruleForm.appliesTo': 'S’applique à',
  'admin.ruleForm.typeOption': { one: '{name} — {count} équipement', other: '{name} — {count} équipements' },
  'admin.ruleForm.appliesToHint': 'Chaque équipement de ce type en hérite, chacun avec son propre planning.',
  'admin.ruleForm.titleField': 'Travail à effectuer',
  'admin.ruleForm.titlePlaceholder': 'Remplacer les filtres à air',
  'admin.ruleForm.instructions': 'Consignes',
  'admin.ruleForm.instructionsPlaceholder': 'Rédigez-les comme vous les expliqueriez à quelqu’un qui fait ce travail pour la première fois.',
  'admin.ruleForm.instructionsHint': 'Affichées au technicien sur son téléphone, juste au-dessus du formulaire d’intervention.',
  'admin.ruleForm.howOften': 'Fréquence',
  'admin.ruleForm.everyPrefix': 'Intervalle :',
  'admin.ruleForm.intervalValue': 'Valeur de l’intervalle',
  'admin.ruleForm.intervalUnit': 'Unité de l’intervalle',
  'admin.ruleForm.cadenceEcho': '{cadence} — après chaque intervention, la tâche suivante arrive à échéance un intervalle plus tard, à compter du jour où le travail a réellement été effectué.',
  'admin.ruleForm.active': 'Active',
  'admin.ruleForm.deactivated': 'Désactivée',
  'admin.ruleForm.activeHint': 'Apparaît dans l’application technicien pour chaque équipement de ce type.',
  'admin.ruleForm.deactivatedHint': 'Les tâches en attente sont masquées et conservent leurs échéances. L’historique est préservé.',
  'admin.ruleForm.frequencyChange': 'Changement de fréquence',
  'admin.ruleForm.frequencyChangeBody': 'Les tâches en attente conservent les échéances qu’elles ont déjà. Le nouvel intervalle s’applique à partir de la prochaine tâche générée après une intervention. Pour déplacer une tâche en attente dès maintenant, replanifiez-la explicitement.',
  'admin.ruleForm.customDue': 'Définir moi-même la première échéance',
  'admin.ruleForm.customDueOn': 'Chaque équipement de ce type aura sa première échéance à la date ci-dessous.',
  'admin.ruleForm.customDueOff': 'Par défaut, la première tâche arrive à échéance le {date}.',
  'admin.ruleForm.firstDueDate': 'Première échéance',
  'admin.ruleForm.previewCount': { one: 'Cette tâche sera planifiée sur {count} équipement existant', other: 'Cette tâche sera planifiée sur {count} équipements existants' },
  'admin.ruleForm.previewNone': 'Aucun équipement de ce type pour l’instant',
  'admin.ruleForm.previewBody': 'Chacun conserve son propre planning indépendant, avec une première échéance le {date}. Aucune intervention passée n’est inventée.',
  'admin.ruleForm.previewNoneBody': 'Ajoutez un équipement de ce type et il reprendra cette tâche automatiquement.',

  /* ----------------------------- admin/components/RescheduleDialog.tsx --- */
  'admin.reschedule.title': 'Replanifier cette tâche',
  'admin.reschedule.confirm': 'Déplacer cette tâche',
  'admin.reschedule.currentlyDue': 'Échéance actuelle : {date}',
  'admin.reschedule.shortcut.today': 'Aujourd’hui',
  'admin.reschedule.shortcut.tomorrow': 'Demain',
  'admin.reschedule.shortcut.week': 'Dans 1 semaine',
  'admin.reschedule.shortcut.month': 'Dans 1 mois',
  'admin.reschedule.newDate': 'Nouvelle échéance',
  'admin.reschedule.reason': 'Motif',
  'admin.reschedule.reason.placeholder': 'Pièces en commande, prestataire indisponible, site fermé…',
  'admin.reschedule.reason.hint': 'Facultatif — mais c’est ce qui rend le journal d’activité utile à relire plus tard.',
  'admin.reschedule.note': 'Cela déplace uniquement cette tâche, sur ce seul équipement. Une fois le travail terminé, la tâche suivante reste calculée à partir du jour où il a réellement été effectué.',
  'admin.reschedule.toast.done': 'Tâche replanifiée',
  'admin.reschedule.toast.doneBody': '{rule} sur {equipment} arrive désormais à échéance le {date}.',
  'admin.reschedule.toast.noChange': 'Rien à modifier',
  'admin.reschedule.toast.noChangeBody': 'Cette tâche est déjà prévue à cette date, ou elle vient d’être terminée.',
  'admin.reschedule.toast.failed': 'Impossible de replanifier',

  /* -------------------------------- admin/components/ArchiveDialog.tsx --- */
  'admin.archive.title': 'Archiver {name} ?',
  'admin.archive.subtitle.equipment': 'Cet équipement n’apparaîtra plus dans les écrans de configuration.',
  'admin.archive.subtitle.rule': 'Cette maintenance n’apparaîtra plus dans les écrans de configuration.',
  'admin.archive.subtitle.type': 'Ce type d’équipement n’apparaîtra plus dans les écrans de configuration.',
  'admin.archive.records': { one: '{count} intervention terminée reste exactement telle quelle.', other: '{count} interventions terminées restent exactement telles quelles.' },
  'admin.archive.recordsWhy': { one: 'Elle conserve sa propre copie des informations, l’archivage ne peut donc pas en modifier le contenu.', other: 'Chacune conserve sa propre copie des informations, l’archivage ne peut donc pas en modifier le contenu.' },
  'admin.archive.pending': { one: '{count} tâche en attente sera masquée.', other: '{count} tâches en attente seront masquées.' },
  'admin.archive.pendingKept': { one: 'Elle n’est pas supprimée.', other: 'Elles ne sont pas supprimées.' },
  'admin.archive.nothingDeleted': 'Rien n’est supprimé de la base de données. L’archivage permet de retirer du service un élément auquel l’historique fait encore référence.',
  'admin.archive.keep': 'Conserver',
  'admin.archive.confirm': 'Archiver',
  'admin.archive.done': 'Archivé : {name}',
  'admin.archive.doneBody': 'Son historique d’interventions reste intact et consultable.',
  'admin.archive.failed': 'Impossible d’archiver',

  /* ------------------------------ admin/components/CompletionSheet.tsx --- */
  'admin.completion.title': 'Maintenance terminée',
  'admin.completion.photoAlt': 'Photo envoyée pour {task} sur {equipment}',
  'admin.completion.submittedBy': 'Envoyée par {name}',
  'admin.completion.fact.equipmentType': 'Type d’équipement',
  'admin.completion.fact.scheduledFor': 'Prévue le',
  'admin.completion.fact.completed': 'Terminée le',
  'admin.completion.fact.punctuality': 'Ponctualité',
  'admin.completion.fact.carriedOutBy': 'Réalisée par',
  'admin.completion.fact.frequency': 'Fréquence ce jour-là',
  'admin.completion.punctuality.onTheDay': 'Le jour prévu',
  'admin.completion.punctuality.early': { one: '{count} jour d’avance', other: '{count} jours d’avance' },
  'admin.completion.punctuality.late': { one: '{count} jour de retard', other: '{count} jours de retard' },
  'admin.completion.note': 'Commentaire du technicien',
  'admin.completion.noNote': 'Aucun commentaire n’a été laissé.',
  'admin.completion.instructions': 'Consignes en vigueur ce jour-là',
  'admin.completion.immutable': 'Cet enregistrement est définitif. Il conserve les informations de l’équipement et de la maintenance telles qu’elles étaient ce jour-là, quels que soient les changements intervenus depuis.',

  /* ------------------------------------------ admin/screens/SignIn.tsx --- */
  'admin.signIn.lede': 'Connectez-vous pour configurer les équipements, suivre le planning et consulter les interventions terminées.',
  'admin.signIn.email': 'E-mail',
  'admin.signIn.email.placeholder': 'vous@entreprise.com',
  'admin.signIn.password': 'Mot de passe',
  'admin.signIn.workerHint': 'Les techniciens se connectent à l’application technicien. Celle-ci est réservée aux administrateurs.',
  'admin.signIn.demo': 'Administrateur de démonstration —',

  /* --------------------------------------- admin/screens/Dashboard.tsx --- */
  'admin.dashboard.title': 'Vue d’ensemble',
  'admin.dashboard.lede.estate': { one: '{count} équipement actif sur {types}', other: '{count} équipements actifs sur {types}' },
  'admin.dashboard.lede.types': { one: '{count} type', other: '{count} types' },
  'admin.dashboard.refresh': 'Actualiser',
  'admin.dashboard.refreshing': 'Actualisation',
  'admin.dashboard.tile.equipment.label': 'Équipements actifs',
  'admin.dashboard.tile.equipment.deactivated': { one: '{count} équipement désactivé', other: '{count} équipements désactivés' },
  'admin.dashboard.tile.equipment.allActive': 'Tous en service',
  'admin.dashboard.tile.overdue.oldest': { one: 'Retard le plus ancien : {count} jour', other: 'Retard le plus ancien : {count} jours' },
  'admin.dashboard.tile.overdue.none': 'Aucun retard',
  'admin.dashboard.tile.today.scheduled': 'Prévu le {date}',
  'admin.dashboard.tile.today.none': 'Rien de prévu aujourd’hui',
  'admin.dashboard.tile.week.label': '7 prochains jours',
  'admin.dashboard.tile.week.outstanding': { one: '{count} tâche en attente au total', other: '{count} tâches en attente au total' },
  'admin.dashboard.load.title': 'Les quinze prochains jours',
  'admin.dashboard.load.pressure': { one: '{count} tâche à traiter aujourd’hui au plus tard', other: '{count} tâches à traiter aujourd’hui au plus tard' },
  'admin.dashboard.load.clear': 'Aucun retard — le planning est à jour',
  'admin.dashboard.load.open': 'Ouvrir la liste des tâches',
  'admin.dashboard.load.empty.title': 'Rien n’est planifié',
  'admin.dashboard.load.empty.body': 'Chaque équipement est soit désactivé, soit sans maintenance active. Ajoutez-en une et un planning s’ouvrira ici.',
  'admin.dashboard.load.empty.action': 'Ajouter une maintenance',
  'admin.dashboard.setup.title': 'Rien de configuré pour l’instant',
  'admin.dashboard.setup.body': 'Commencez par un type d’équipement, définissez la maintenance dont il a besoin, puis ajoutez les équipements physiques. Chacun aura son propre planning.',
  'admin.dashboard.setup.action': 'Créer le premier type',
  'admin.dashboard.load.scale': 'Tâches à échéance par jour',
  'admin.dashboard.load.peak': { one: 'Pic : {count} tâche', other: 'Pic : {count} tâches' },
  'admin.dashboard.load.axisToday': 'Auj.',
  'admin.dashboard.load.tip': { one: '{weekday} {date} : {count} tâche', other: '{weekday} {date} : {count} tâches' },
  'admin.dashboard.load.tipCarried': { one: '{date} : {count} tâche, dont {carried} en retard', other: '{date} : {count} tâches, dont {carried} en retard' },
  'admin.dashboard.ontime.title': 'Taux de ponctualité',
  'admin.dashboard.ontime.subtitle': 'Terminées dans les délais, sur les trente derniers jours',
  'admin.dashboard.ontime.open': 'Voir l’historique',
  'admin.dashboard.ontime.met': { one: 'Échéance respectée : {onTime} sur {count} intervention', other: 'Échéance respectée : {onTime} sur {count} interventions' },
  'admin.dashboard.ontime.total': { one: '{count} intervention enregistrée au total', other: '{count} interventions enregistrées au total' },
  'admin.dashboard.ontime.spark': 'Activité sur 28 jours',
  'admin.dashboard.attention.title': 'À traiter en priorité',
  'admin.dashboard.attention.subtitle': { one: '{count} tâche en retard', other: '{count} tâches en retard' },
  'admin.dashboard.attention.none': 'Aucune tâche en retard',
  'admin.dashboard.attention.open': 'Voir tous les retards',
  'admin.dashboard.attention.empty.title': 'Tout est à jour',
  'admin.dashboard.attention.empty.body': 'Aucune maintenance n’a dépassé son échéance. Les prochaines tâches sont planifiées ci-dessous.',
  'admin.dashboard.recent.title': 'Dernières interventions',
  'admin.dashboard.recent.subtitle': 'Envoyées depuis l’application technicien',
  'admin.dashboard.recent.open': 'Historique complet',
  'admin.dashboard.recent.empty.title': 'Aucune intervention pour l’instant',
  'admin.dashboard.recent.empty.body': 'Les interventions envoyées par l’équipe apparaîtront ici, photo à l’appui.',
  'admin.dashboard.types.title': 'Types d’équipement',
  'admin.dashboard.types.subtitle': { one: '{count} type · {tasks}', other: '{count} types · {tasks}' },
  'admin.dashboard.types.tasks': { one: '{count} tâche de maintenance active', other: '{count} tâches de maintenance actives' },
  'admin.dashboard.types.open': 'Gérer les types',
  'admin.dashboard.next.title': 'À venir',
  'admin.dashboard.next.subtitle': 'Les prochaines tâches planifiées',
  'admin.dashboard.next.open': 'Voir le planning',
  'admin.dashboard.next.empty.title': 'Rien de planifié',
  'admin.dashboard.next.empty.body': 'Ajoutez un équipement ou une tâche de maintenance pour créer un planning.',
  'admin.dashboard.hidden.body': { one: '{count} tâche en attente est masquée car son équipement ou sa tâche de maintenance est désactivée. Elle conserve son échéance et réapparaît dès la réactivation.', other: '{count} tâches en attente sont masquées car leur équipement ou leur tâche de maintenance est désactivée. Elles conservent leurs échéances et réapparaissent dès la réactivation.' },
  'admin.dashboard.hidden.action': 'Les afficher',

  /* --------------------------------------- admin/screens/TaskBoard.tsx --- */
  'admin.tasks.title': 'Travaux en attente',
  'admin.tasks.outstandingCount': { one: '{count} tâche en attente', other: '{count} tâches en attente' },
  'admin.tasks.loading': 'Chargement du planning…',
  'admin.tasks.refresh': 'Actualiser',
  'admin.tasks.bucket.all': 'Tout',
  'admin.tasks.filter.status': 'Filtrer par statut d’échéance',
  'admin.tasks.filter.dueOn': 'Échéance : {date}',
  'admin.tasks.filter.clearDate': 'Effacer le filtre de date',
  'admin.tasks.search.placeholder': 'Rechercher par code d’actif, nom, emplacement ou tâche',
  'admin.tasks.search.label': 'Rechercher dans les travaux en attente',
  'admin.tasks.search.clear': 'Effacer la recherche',
  'admin.tasks.filter.type': 'Filtrer par type d’équipement',
  'admin.tasks.filter.allTypes': 'Tous les types',
  'admin.tasks.filter.equipment': 'Filtrer par équipement',
  'admin.tasks.filter.allEquipment': 'Tous les équipements',
  'admin.tasks.includeHidden': 'Inclure les masquées',
  'admin.tasks.empty.title': 'Aucun travail en attente',
  'admin.tasks.empty.body': 'Toutes les tâches planifiées sont terminées. De nouvelles tâches apparaîtront à leur échéance.',
  'admin.tasks.empty.filtered': 'Aucun résultat pour ces filtres',
  'admin.tasks.empty.filteredBody': 'Élargissez la recherche ou effacez les filtres pour voir tout le planning.',
  'admin.tasks.empty.clearFilters': 'Effacer les filtres',
  'admin.tasks.truncated': 'Affichage des {shown} tâches les plus urgentes sur les {total} en attente — les compteurs ci-dessus les incluent toutes. Filtrez par type ou par équipement, ou lancez une recherche, pour voir les autres.',

  /* ----------------------------------- admin/screens/EquipmentList.tsx --- */
  'admin.equipment.title': 'Équipements',
  'admin.equipment.lede.count': { one: '{count} équipement affiché · une fiche par élément physique présent sur le site', other: '{count} équipements affichés · une fiche par élément physique présent sur le site' },
  'admin.equipment.lede.loading': 'Chargement du parc…',
  'admin.equipment.add': 'Ajouter un équipement',
  'admin.equipment.filter.scope': 'Filtrer par statut',
  'admin.equipment.scope.active': 'En service',
  'admin.equipment.scope.inactive': 'Désactivés',
  'admin.equipment.scope.all': 'Tout',
  'admin.equipment.search.placeholder': 'Rechercher par code, nom ou emplacement',
  'admin.equipment.search.aria': 'Rechercher un équipement',
  'admin.equipment.search.clear': 'Effacer la recherche',
  'admin.equipment.filter.type': 'Filtrer par type',
  'admin.equipment.filter.allTypes': 'Tous les types',
  'admin.equipment.filter.typeOption': '{name} ({count})',
  'admin.equipment.empty.title': 'Aucun équipement pour l’instant',
  'admin.equipment.empty.body': 'Ajoutez votre premier équipement et il héritera de toutes les maintenances définies pour son type.',
  'admin.equipment.empty.filtered.title': 'Aucun résultat',
  'admin.equipment.empty.filtered.body': 'Essayez une autre recherche, ou effacez le filtre par type.',
  'admin.equipment.card.deactivated': 'Désactivé',
  'admin.equipment.card.noLocation': 'Emplacement non renseigné',
  'admin.equipment.card.scheduled': { one: 'planifiée', other: 'planifiées' },
  'admin.equipment.card.completed': { one: 'terminée', other: 'terminées' },
  'admin.equipment.card.next': 'Prochaine le {date}',
  'admin.equipment.card.noSchedule': 'Aucune échéance',
  'admin.equipment.card.lastServiced': 'Dernière intervention {when}',
  'admin.equipment.card.neverServiced': 'Aucune intervention',

  /* --------------------------------- admin/screens/EquipmentDetail.tsx --- */
  'admin.equipmentDetail.backToEquipment': 'Équipements',
  'admin.equipmentDetail.flag.deactivated': 'Désactivé',
  'admin.equipmentDetail.rule.deactivatedFlag': 'Désactivée',
  'admin.equipmentDetail.noLocation': 'Emplacement non renseigné',
  'admin.equipmentDetail.lastServiced': 'Dernière intervention {when}',
  'admin.equipmentDetail.neverServiced': 'Aucune intervention',
  'admin.equipmentDetail.stat.scheduled': 'Planifiées',
  'admin.equipmentDetail.stat.completed': 'Terminées',
  'admin.equipmentDetail.stat.nextDue': 'Prochaine',
  'admin.equipmentDetail.action.edit': 'Modifier',
  'admin.equipmentDetail.action.duplicate': 'Dupliquer',
  'admin.equipmentDetail.action.deactivate': 'Désactiver',
  'admin.equipmentDetail.action.reactivate': 'Réactiver',
  'admin.equipmentDetail.action.archive': 'Archiver',
  'admin.equipmentDetail.tabs.aria': 'Sections de la fiche de l’équipement',
  'admin.equipmentDetail.tab.schedule': 'Planning',
  'admin.equipmentDetail.tab.history': 'Historique',
  'admin.equipmentDetail.tab.activity': 'Activité',
  'admin.equipmentDetail.reactivated': 'Remis en service',
  'admin.equipmentDetail.reactivatedBody': 'Ses tâches en attente sont de nouveau visibles, à leurs échéances actuelles.',
  'admin.equipmentDetail.deactivated': 'Désactivé',
  'admin.equipmentDetail.deactivatedBody': 'Les tâches en attente sont masquées et conservent leurs dates. L’historique des interventions reste intact.',
  'admin.equipmentDetail.updateFailed': 'Mise à jour impossible',
  'admin.equipmentDetail.empty.scheduleTitle': 'Aucune maintenance planifiée',
  'admin.equipmentDetail.empty.scheduleBody': 'Ajoutez une maintenance à ce type d’équipement et un planning apparaîtra ici automatiquement.',
  'admin.equipmentDetail.empty.addTask': 'Ajouter une maintenance',
  'admin.equipmentDetail.empty.hiddenTitle': 'Planning masqué : équipement désactivé',
  'admin.equipmentDetail.empty.hiddenBody': 'Ses tâches en attente existent toujours et conservent leurs échéances. Réactivez l’équipement pour les afficher de nouveau.',
  'admin.equipmentDetail.empty.historyTitle': 'Aucune intervention enregistrée',
  'admin.equipmentDetail.empty.historyBody': 'Les interventions envoyées depuis l’application technicien apparaissent ici, avec la photo, la personne et l’heure exacte.',
  'admin.equipmentDetail.empty.activityTitle': 'Aucune modification enregistrée',
  'admin.equipmentDetail.empty.activityBody': 'Les modifications de configuration et les replanifications de cet équipement seront répertoriées ici.',
  'admin.equipmentDetail.hiddenNote': { one: '{count} tâche en attente est masquée car la maintenance ou l’équipement est désactivé. Les dates sont conservées.', other: '{count} tâches en attente sont masquées car la maintenance ou l’équipement est désactivé. Les dates sont conservées.' },
  'admin.equipmentDetail.inheritedFrom': 'Hérité de {type}',
  'admin.equipmentDetail.duplicated': { one: '{code} créé', other: '{count} équipements créés' },
  'admin.equipmentDetail.duplicatedBody': 'Chacun reçoit un nouvel identifiant et un planning vierge. Aucun historique n’a été copié.',
  'admin.equipmentDetail.duplicate.title': 'Dupliquer cet équipement',
  'admin.equipmentDetail.duplicate.subtitle': 'À partir de {code}',
  'admin.equipmentDetail.duplicate.note': 'Une copie est un nouvel équipement physique : elle reçoit son propre code d’actif et un planning qui repart de zéro aujourd’hui. L’historique des interventions n’est jamais copié — il appartient à l’équipement d’origine.',
  'admin.equipmentDetail.duplicate.codeLabel': 'Code d’actif',
  'admin.equipmentDetail.duplicate.hintOne': 'Laissez vide pour ajouter -COPY au code d’origine.',
  'admin.equipmentDetail.duplicate.hintMany': 'Un suffixe à deux chiffres est ajouté à chaque copie.',
  'admin.equipmentDetail.duplicate.countLabel': 'Quantité',
  'admin.equipmentDetail.duplicate.firstDue': 'Pour chaque copie, la première échéance tombe un intervalle après le {date}.',
  'admin.equipmentDetail.duplicate.submit': { one: 'Créer une copie', other: 'Créer {count} copies' },
  'admin.equipmentDetail.duplicate.failed': 'Duplication impossible',

  /* ---------------------------------------- admin/screens/RuleList.tsx --- */
  'admin.rules.title': 'Maintenance',
  'admin.rules.lede': { one: '{count} maintenance sur {types} · chaque équipement d’un type conserve son propre planning', other: '{count} maintenances réparties sur {types} · chaque équipement d’un type conserve son propre planning' },
  'admin.rules.lede.types': { one: '{count} type d’équipement', other: '{count} types d’équipement' },
  'admin.rules.add': 'Nouvelle maintenance',
  'admin.rules.filter.scope': 'Filtrer par statut',
  'admin.rules.scope.all': 'Toutes',
  'admin.rules.scope.active': 'Actives',
  'admin.rules.scope.inactive': 'Inactives',
  'admin.rules.filter.type': 'Filtrer par type d’équipement',
  'admin.rules.filter.allTypes': 'Tous les types',
  'admin.rules.filter.typeOption': '{name} ({count})',
  'admin.rules.empty.filtered.title': 'Aucun résultat',
  'admin.rules.empty.filtered.body': 'Essayez d’effacer les filtres.',
  'admin.rules.empty.title': 'Aucune maintenance définie pour l’instant',
  'admin.rules.empty.body': 'Définissez ce qu’il faut faire et à quelle fréquence. Chaque équipement du type choisi en hérite aussitôt.',
  'admin.rules.group.count': { one: '{count} maintenance', other: '{count} maintenances' },
  'admin.rules.group.add': 'Ajouter',
  'admin.rules.card.deactivated': 'Inactive',
  'admin.rules.card.noInstructions': 'Aucune consigne rédigée pour l’instant.',
  'admin.rules.card.scheduled': { one: '{count} planifiée', other: '{count} planifiées' },
  'admin.rules.card.completions': { one: '{count} intervention', other: '{count} interventions' },

  /* -------------------------------------- admin/screens/RuleDetail.tsx --- */
  'admin.ruleDetail.backToRules': 'Maintenance',
  'admin.ruleDetail.reactivated': 'Réactivée',
  'admin.ruleDetail.reactivatedBody': 'Les tâches en attente sont de nouveau visibles, à leurs échéances actuelles, y compris celles en retard.',
  'admin.ruleDetail.deactivated': 'Désactivée',
  'admin.ruleDetail.deactivatedBody': 'Les tâches en attente sont masquées et conservent leurs dates. L’historique des interventions reste intact.',
  'admin.ruleDetail.updateFailed': 'Mise à jour impossible',
  'admin.ruleDetail.flag.deactivated': 'Inactive',
  'admin.ruleDetail.noInstructions': 'Aucune consigne rédigée pour l’instant — les techniciens ne voient que le titre.',
  'admin.ruleDetail.stat.scheduled': 'Planifiées',
  'admin.ruleDetail.stat.completed': 'Terminées',
  'admin.ruleDetail.action.edit': 'Modifier',
  'admin.ruleDetail.action.deactivate': 'Désactiver',
  'admin.ruleDetail.action.reactivate': 'Réactiver',
  'admin.ruleDetail.action.archive': 'Archiver',
  'admin.ruleDetail.tabs.aria': 'Sections',
  'admin.ruleDetail.tab.schedule': 'Planning',
  'admin.ruleDetail.tab.history': 'Historique',
  'admin.ruleDetail.tab.activity': 'Activité',
  'admin.ruleDetail.empty.scheduleTitle': 'Aucun équipement de ce type pour l’instant',
  'admin.ruleDetail.empty.scheduleBody': 'Ajoutez un équipement de ce type et il héritera de cette maintenance, avec son propre planning.',
  'admin.ruleDetail.empty.hiddenTitle': 'Plannings masqués : maintenance désactivée',
  'admin.ruleDetail.empty.hiddenBody': 'Toutes les tâches en attente existent toujours et conservent leur date. Réactivez la maintenance pour les afficher de nouveau.',
  'admin.ruleDetail.empty.seeEquipment': 'Voir les équipements',
  'admin.ruleDetail.hiddenNote': { one: '{count} tâche en attente est masquée car son équipement est désactivé. Les dates sont conservées.', other: '{count} tâches en attente sont masquées car leur équipement est désactivé. Les dates sont conservées.' },
  'admin.ruleDetail.empty.historyTitle': 'Pas encore effectuée',
  'admin.ruleDetail.empty.historyBody': 'Dès que cette maintenance sera effectuée, chaque intervention apparaîtra ici avec sa photo.',
  'admin.ruleDetail.empty.activityTitle': 'Aucune modification enregistrée',

  /* ---------------------------------------- admin/screens/TypeList.tsx --- */
  'admin.types.title': 'Types d’équipement',
  'admin.types.lede': 'Définissez la maintenance une seule fois par type. Chaque équipement de ce type en hérite, avec son propre planning.',
  'admin.types.add': 'Nouveau type',
  'admin.types.empty.title': 'Aucun type d’équipement pour l’instant',
  'admin.types.empty.body': 'Commencez par un type — « Unité CVC », « Chariot élévateur », « Extincteur » — puis définissez la maintenance dont il a besoin.',
  'admin.types.toast.archived': 'Type archivé',
  'admin.types.toast.archivedBody': 'Son historique est conservé et reste consultable.',
  'admin.types.toast.archiveFailed': 'Archivage impossible',
  'admin.types.card.edit': 'Modifier {name}',
  'admin.types.card.inService': { one: 'en service', other: 'en service' },
  'admin.types.card.equipmentDeactivated': { one: '{count} désactivé', other: '{count} désactivés' },
  'admin.types.card.tasks': { one: 'tâche', other: 'tâches' },
  'admin.types.card.tasksDeactivated': { one: '{count} désactivée', other: '{count} désactivées' },
  'admin.types.card.equipmentLink': 'Équipements',
  'admin.types.card.maintenanceLink': 'Maintenance',
  'admin.types.toast.updated': 'Type mis à jour',
  'admin.types.toast.added': '« {name} » ajouté',
  'admin.types.toast.addedBody': 'Définissez à présent la maintenance dont il a besoin.',
  'admin.types.form.saveFailed': 'Enregistrement impossible. Veuillez réessayer.',
  'admin.types.form.editTitle': 'Modifier le type d’équipement',
  'admin.types.form.newTitle': 'Nouveau type d’équipement',
  'admin.types.form.archive': 'Archiver',
  'admin.types.form.save': 'Enregistrer',
  'admin.types.form.create': 'Créer le type',
  'admin.types.form.name': 'Nom',
  'admin.types.form.namePlaceholder': 'Unité CVC',
  'admin.types.form.colour': 'Couleur',
  'admin.types.form.symbol': 'Symbole',
  'admin.types.form.archiveNote': 'L’archivage masque un type et ses tâches de maintenance. Il n’est possible que lorsque plus aucun équipement ne l’utilise. L’historique des interventions terminées est toujours conservé — il contient sa propre copie des détails.',
  'admin.types.accent.aurora': 'Aurore boréale',
  'admin.types.accent.ice': 'Glace',
  'admin.types.accent.cobalt': 'Cobalt',
  'admin.types.accent.orchid': 'Orchidée',
  'admin.types.accent.ember': 'Braise',
  'admin.types.accent.sunset': 'Coucher de soleil',
  'admin.types.accent.gold': 'Or',
  'admin.types.accent.lime': 'Vert citron',
  'admin.types.symbol.cube': 'Cube',
  'admin.types.symbol.fan': 'Ventilateur',
  'admin.types.symbol.bolt': 'Éclair',
  'admin.types.symbol.drop': 'Goutte',
  'admin.types.symbol.gear': 'Engrenage',
  'admin.types.symbol.flame': 'Flamme',
  'admin.types.symbol.wave': 'Onde',
  'admin.types.symbol.shield': 'Bouclier',
  'admin.types.symbol.truck': 'Camion',
  'admin.types.symbol.leaf': 'Feuille',
  'admin.types.symbol.chip': 'Puce',
  'admin.types.symbol.lift': 'Ascenseur',

  /* ----------------------------------- admin/screens/HistoryScreen.tsx --- */
  'admin.history.title': 'Historique des interventions',
  'admin.history.lede.filtered': { one: '{count} intervention correspondant à vos filtres · chacune avec sa photo', other: '{count} interventions correspondant à vos filtres · chacune avec sa photo' },
  'admin.history.lede.all': { one: '{count} intervention enregistrée · chacune avec sa photo', other: '{count} interventions enregistrées · chacune avec sa photo' },
  'admin.history.search.placeholder': 'Rechercher par équipement, tâche, personne ou commentaire',
  'admin.history.search.aria': 'Rechercher dans l’historique',
  'admin.history.search.clear': 'Effacer la recherche',
  'admin.history.filter.type': 'Filtrer par type',
  'admin.history.filter.allTypes': 'Tous les types',
  'admin.history.filter.person': 'Filtrer par personne',
  'admin.history.filter.anyone': 'Tous',
  'admin.history.filter.fromDate': 'Date de début',
  'admin.history.filter.toDate': 'Date de fin',
  'admin.history.filter.rangeTo': 'au',
  'admin.history.range.last7': '7 derniers jours',
  'admin.history.range.last30': '30 derniers jours',
  'admin.history.empty.filtered.title': 'Aucun résultat pour ces filtres',
  'admin.history.empty.filtered.body': 'Élargissez la période ou effacez les filtres.',
  'admin.history.empty.title': 'Aucune intervention pour l’instant',
  'admin.history.empty.body': 'Quand l’équipe envoie une intervention depuis l’application technicien, elle apparaît ici — photo, personne et heure exacte de l’enregistrement.',
  'admin.history.empty.clearFilters': 'Effacer les filtres',
  'admin.history.empty.seeTasks': 'Voir les tâches en attente',
  'admin.history.showMore': { one: 'Afficher {count} de plus', other: 'Afficher {count} de plus' },
  'admin.history.more.shown': 'Affichage de {shown} sur {total}',
  'admin.history.more.shownRange': 'Affichage de {shown} sur {total} · du {from} au {to}',
  'admin.history.more.shownFrom': 'Affichage de {shown} sur {total} · à partir du {from}',
  'admin.history.more.shownTo': 'Affichage de {shown} sur {total} · jusqu’au {to}',
  'admin.history.end': { one: 'C’est tout : {count} intervention.', other: 'C’est tout : {count} interventions.' },

  /* ---------------------------------- admin/screens/ActivityScreen.tsx --- */
  'admin.activity.title': 'Journal d’activité',
  'admin.activity.lede': 'Chaque modification de configuration et chaque replanification, avec son auteur et sa date.',
  'admin.activity.filter.aria': 'Filtrer le journal d’activité',
  'admin.activity.scope.all': 'Tout',
  'admin.activity.scope.schedule': 'Replanifications',
  'admin.activity.scope.config': 'Configuration',
  'admin.activity.empty.title': 'Aucune entrée pour l’instant',
  'admin.activity.empty.body': 'Les modifications apportées aux équipements, aux types, aux maintenances et aux plannings apparaîtront ici.',
  'admin.activity.detail.reason': '« {reason} »',

  /* ----------------------------------------- worker/screens/SignIn.tsx --- */
  'worker.signIn.lede': 'Connectez-vous pour voir les tâches du jour.',
  'worker.signIn.email': 'E-mail',
  'worker.signIn.email.placeholder': 'vous@entreprise.com',
  'worker.signIn.password': 'Mot de passe',
  'worker.signIn.demo': 'Démo —',

  /* --------------------------------------- worker/screens/TaskList.tsx --- */
  'worker.list.greeting.morning': 'Bonjour, {name}',
  'worker.list.greeting.afternoon': 'Bon après-midi, {name}',
  'worker.list.greeting.evening': 'Bonsoir, {name}',
  'worker.list.title.clear': 'Rien pour aujourd’hui',
  'worker.list.title.toDo': { one: '{count} à faire', other: '{count} à faire' },
  'worker.list.refresh': 'Actualiser la liste',
  'worker.list.toggleTheme': 'Changer d’apparence',
  'worker.list.searchPlaceholder': 'Code d’actif, nom ou emplacement',
  'worker.list.searchLabel': 'Rechercher des tâches',
  'worker.list.empty.noMatchTitle': 'Aucun résultat',
  'worker.list.empty.noMatchBody': 'Essayez un autre code d’actif ou un autre emplacement.',
  'worker.list.empty.clearTitle': 'Tout est à jour',
  'worker.list.empty.clearBody': 'Toutes les tâches prévues ont été effectuées. Les nouvelles apparaîtront ici à leur échéance.',
  'worker.list.clearSearch': 'Effacer la recherche',
  'worker.list.show': 'Afficher',
  'worker.list.hide': 'Masquer',
  'worker.list.truncated': { one: 'Affichage de {shown} tâche sur {count}. Utilisez la recherche pour en trouver une en particulier.', other: 'Affichage des {shown} tâches les plus urgentes sur {count}. Utilisez la recherche pour en trouver une en particulier.' },
  'worker.list.footer': { one: '{count} tâche en attente · heures en {zone}', other: '{count} tâches en attente · heures en {zone}' },

  /* ------------------------------------- worker/screens/TaskDetail.tsx --- */
  'worker.detail.allJobs': 'Les tâches',
  'worker.detail.gone': 'Cette tâche n’est plus en attente.',
  'worker.detail.goneDetail': 'Quelqu’un l’a peut-être terminée, ou elle a peut-être été désactivée.',
  'worker.detail.backToList': 'Retour à la liste',
  'worker.detail.sessionEnded': 'Votre session a expiré. Reconnectez-vous, la tâche sera toujours là.',
  'worker.detail.stillOpen': 'Une erreur s’est produite. La tâche est toujours ouverte — réessayez.',
  'worker.detail.toast.alreadyDone': 'Déjà terminée',
  'worker.detail.toast.alreadyDoneBody': 'Quelqu’un d’autre l’a envoyée avant vous. Voici la liste à jour.',
  'worker.detail.where': 'Lieu',
  'worker.detail.noLocation': 'Non renseigné',
  'worker.detail.due': 'Échéance',
  'worker.detail.instructions': 'Consignes',
  'worker.detail.finish': 'Terminer la tâche',
  'worker.detail.check': 'Maintenance terminée',
  'worker.detail.photoHint': 'Une photo montrant le travail effectué. Elle est conservée avec l’intervention et seuls les administrateurs peuvent la voir.',
  'worker.detail.comment': 'Quelque chose à ajouter ?',
  'worker.detail.comment.placeholder': 'Facultatif — pièces utilisées, une observation, tout ce qui pourrait servir la prochaine fois.',
  'worker.detail.missing.tick': 'Cochez d’abord « Maintenance terminée »',
  'worker.detail.missing.photo': 'Ajoutez une photo du travail effectué',
  'worker.detail.submitting': 'Envoi en cours…',
  'worker.detail.submit': 'Envoyer l’intervention',
  'worker.detail.submit.progress': { one: 'Envoyer — {count} étape sur 2', other: 'Envoyer — {count} étapes sur 2' },

  /* ------------------------------ worker/components/SuccessOverlay.tsx --- */
  'worker.success.title': 'Enregistré. Bravo !',
  'worker.success.next': 'Prochaine fois : {date}',
  'worker.success.inDays': { one: 'dans {count} jour', other: 'dans {count} jours' },
  'worker.success.backToList': 'Retour à la liste',
};
