import type { Dictionary } from '../i18n';

/**
 * Português europeu.
 *
 * Portugal, not Brazil: "casa de banho" not "banheiro", "equipa" not "time",
 * and the second person is «você» only where a form addresses somebody
 * directly — most of this interface simply states facts, which reads better
 * impersonally in Portuguese than a literal translation of English's "you".
 *
 * Typed as `Dictionary`, so a key missing from here is a build error.
 */
export const pt: Dictionary = {
  /* --------------------------------------------------------- common --- */
  'common.loading': 'A carregar…',
  'common.retry': 'Tentar novamente',
  'common.cancel': 'Cancelar',
  'common.save': 'Guardar',
  'common.close': 'Fechar',
  'common.clear': 'Limpar',
  'common.search': 'Procurar',
  'common.back': 'Voltar',
  'common.signOut': 'Terminar sessão',
  'common.signIn': 'Entrar',
  'common.optional': 'Opcional',
  'common.none': 'Nenhum',
  'common.appearance': 'Aspeto',
  'common.language': 'Idioma',
  'common.somethingWrong': 'Algo correu mal. Tente novamente.',
  'common.offline': 'Não foi possível contactar o servidor. Tente novamente.',

  /* -------------------------------------------------------- settings --- */
  'theme.dark': 'Escuro',
  'theme.light': 'Claro',
  'theme.system': 'Sistema',
  'lang.choose': 'Escolher idioma',
  'lang.changed': 'Idioma alterado',
  'lang.changedBody': 'A aplicação está agora em português.',

  /* ---------------------------------------------------------- status --- */
  'status.overdue': 'Em atraso',
  'status.overdue.short': 'Em atraso',
  'status.today': 'Para hoje',
  'status.today.short': 'Hoje',
  'status.soon': 'Para esta semana',
  'status.soon.short': 'Esta semana',
  'status.later': 'Agendado',
  'status.later.short': 'Mais tarde',

  /* ------------------------------------------------------------- due --- */
  'due.overdue': { one: '1 dia de atraso', other: '{count} dias de atraso' },
  'due.today': 'Para hoje',
  'due.tomorrow': 'Para amanhã',
  'due.inDays': { one: 'Daqui a 1 dia', other: 'Daqui a {count} dias' },
  'due.overdueShort': { one: '{count}d de atraso', other: '{count}d de atraso' },
  'due.earlyShort': { one: '{count}d adiantado', other: '{count}d adiantado' },
  'due.onTheDay': 'No próprio dia',

  /* --------------------------------------------------------- urgency --- */
  'urgency.overdue': { one: '1 em atraso', other: '{count} em atraso' },
  'urgency.today': { one: '1 para hoje', other: '{count} para hoje' },
  'urgency.soon': { one: '1 para esta semana', other: '{count} para esta semana' },
  'urgency.clear': 'Não há nada a precisar de atenção',
  'urgency.notLate': 'Nada está atrasado — {list}',
  'urgency.and': '{list} e {last}',

  /* ------------------------------------------------ shared components --- */
  'ui.field.optional': 'Opcional',
  'ui.field.required': 'Obrigatório',
  'ui.photo.take': 'Tirar fotografia',
  'ui.photo.choose': 'Escolher fotografia',
  'ui.photo.retake': 'Substituir fotografia',
  'ui.photo.uploading': 'A enviar…',
  'ui.photo.failed': 'Não foi possível enviar a fotografia. Tente novamente.',
  'ui.photo.tooBig': 'A imagem é demasiado grande. Tire uma nova fotografia e tente novamente.',
  'ui.photo.wrongType': 'Esse ficheiro não é uma imagem. É obrigatória uma fotografia do trabalho.',
  'ui.photo.attached': 'Fotografia anexada',
  'ui.photo.remove': 'Remover fotografia',
  'ui.state.emptyTitle': 'Ainda não há nada aqui',
  'ui.state.errorTitle': 'Algo correu mal',
  'ui.pull.release': 'Largue para atualizar',
  'ui.pull.refreshing': 'A atualizar…',

  /* ------------------------------------------- errors, by server code --- */
  'error.UNAUTHORIZED': 'A sessão terminou. Inicie sessão novamente.',
  'error.FORBIDDEN': 'Não tem permissão para fazer isso.',
  'error.NOT_FOUND': 'Isso já não existe.',
  'error.ALREADY_COMPLETED': 'Já foi concluída — alguém chegou primeiro.',
  'error.EQUIPMENT_INACTIVE': 'Este equipamento foi desativado. Não há nada a submeter.',
  'error.RULE_INACTIVE': 'Esta manutenção foi desativada. Não há nada a submeter.',
  'error.RULE_NOT_APPLICABLE': 'Esta manutenção já não se aplica a este equipamento. Não há nada a submeter.',
  'error.PHOTO_REQUIRED': 'É obrigatória uma fotografia do trabalho concluído.',
  'error.PHOTO_REUSED': 'Essa fotografia já está associada a outra conclusão.',
  'error.DUPLICATE_CODE': 'Esse código de ativo já está a ser utilizado.',
  'error.DUPLICATE_NAME': 'Esse nome já está a ser utilizado.',
  'error.TYPE_IN_USE': 'Esse tipo ainda tem equipamento associado.',
  'error.CONFIRMATION_REQUIRED': 'Confirme antes de continuar.',
  'error.TOO_MANY_ATTEMPTS': 'Demasiadas tentativas. Aguarde um momento e tente novamente.',
  'error.PAYLOAD_TOO_LARGE': 'Esse ficheiro é demasiado grande.',
  'error.BAD_UPLOAD': 'Não foi possível ler o envio. Tente novamente.',
  'error.BAD_JSON': 'Não foi possível ler o pedido. Tente novamente.',
  'error.VALIDATION': 'Verifique o campo assinalado.',
  'error.INTERNAL': 'Ocorreu um erro no servidor. Tente novamente.',
  'error.SIGN_IN': 'O email e a palavra-passe não correspondem a nenhuma conta.',

  /* ------------------------------- field, unit and role names --- */
  'field.typeName': 'Nome do tipo',
  'field.assetCode': 'Código do ativo',
  'field.equipmentName': 'Nome do equipamento',
  'field.equipmentType': 'Tipo de equipamento',
  'field.taskTitle': 'Título da manutenção',
  'unit.days': 'dias',
  'unit.weeks': 'semanas',
  'unit.months': 'meses',
  'unit.years': 'anos',
  'role.admin': 'administrador',
  'role.worker': 'técnico',

  /* ----------------------- messages the server sends, by key --- */
  'server.required': '{field} é obrigatório.',
  'server.tooLong': '{field} não pode ter mais de {max} caracteres.',
  'server.typeNameTaken': 'Já existe um tipo de equipamento chamado «{name}».',
  'server.typeGone': 'Esse tipo de equipamento já não existe.',
  'server.typeInUse': {
    one: 'Ainda há 1 equipamento com este tipo. Mova-o ou arquive-o primeiro.',
    other: 'Ainda há {count} equipamentos com este tipo. Mova-os ou arquive-os primeiro.',
  },
  'server.badFirstDue': 'A primeira data prevista tem de ser uma data válida.',
  'server.pickRealType': 'Escolha um tipo de equipamento que ainda exista.',
  'server.pickRealDate': 'Escolha uma data válida.',
  'server.codeTaken': 'O código de ativo «{code}» já está a ser utilizado.',
  'server.equipmentGone': 'Esse equipamento já não existe.',
  'server.intervalWhole': 'O intervalo tem de ser um número inteiro maior do que zero.',
  'server.intervalUnit': 'A unidade do intervalo tem de ser dias, semanas, meses ou anos.',
  'server.intervalCapped': 'Os intervalos estão limitados a cerca de cinquenta anos, o que em {unit} são {max}.',
  'server.ruleGone': 'Essa manutenção já não existe.',
  'server.taskGone': 'Essa tarefa já não existe.',
  'server.taskNotOutstanding': 'Essa tarefa já não está pendente.',
  'server.completionGone': 'Esse registo de conclusão já não existe.',
  'server.alreadyCompleted': 'Já foi concluída — alguém chegou primeiro.',
  'server.equipmentDeactivated': '{name} foi desativado. Não há nada a submeter.',
  'server.ruleDeactivated': '«{title}» foi desativada. Não há nada a submeter.',
  'server.ruleNotApplicable': '{name} já não é um equipamento de «{title}». Não há nada a submeter.',
  'server.photoRequired': 'É obrigatória uma fotografia do trabalho concluído.',
  'server.photoMissing': 'Não foi possível encontrar essa fotografia. Anexe-a novamente.',
  'server.photoNotYours': 'Essa fotografia foi enviada por outra pessoa.',
  'server.photoReused': 'Essa fotografia já está associada a outra conclusão.',
  'server.photoUnavailable': 'Essa fotografia não está disponível.',
  'server.photoOtherCompletion': 'Essa fotografia pertence a outra conclusão.',
  'server.noPhotoAttached': 'Não foi anexada nenhuma fotografia.',
  'server.badUpload': 'Não foi possível ler o envio. Anexe a fotografia novamente.',
  'server.adminOnly': 'Esta ação é apenas para administradores.',
  'server.roleOnly': 'Esta ação é apenas para {role}.',
  'server.wrongApp': 'Esta é a aplicação de administração. Utilize a aplicação de campo para entrar.',
  'server.tickConfirm': 'Assinale «Manutenção concluída» antes de submeter.',
  'server.addOnePhoto': 'Anexe uma fotografia do trabalho concluído.',
  'server.signInToContinue': 'Inicie sessão para continuar.',
  'server.noAccess': 'Não tem acesso a esta ação.',
  'server.notFound': 'Isso já não existe.',


  /* ------------------------------------ the worker account sheet --- */
  'worker.account.title': 'A sua conta',
  'worker.account.open': 'Conta, idioma e aspeto',


  /* ------------------------------------ ui/components/PhotoCapture.tsx --- */
  'ui.photo.defaultLabel': 'Fotografia do trabalho feito',
  'ui.photo.previewAlt': 'A fotografia que está prestes a enviar',

  /* ----------------------------------------- ui/components/Toaster.tsx --- */
  'ui.toast.dismiss': 'Ignorar',

  /* ------------------------------------------ ui/components/charts.tsx --- */
  'ui.chart.valueTooltip': '{label}: {value}',

  /* --------------------------------------- admin/components/Chrome.tsx --- */
  'admin.nav.sections': 'Secções',
  'admin.nav.overview': 'Vista geral',
  'admin.nav.overview.hint': 'Tudo num relance',
  'admin.nav.outstanding': 'Pendentes',
  'admin.nav.outstanding.hint': 'Trabalho por fazer',
  'admin.nav.equipment': 'Equipamento',
  'admin.nav.equipment.hint': 'Todos os equipamentos das instalações',
  'admin.nav.rules': 'Manutenção',
  'admin.nav.rules.hint': 'O que é feito, com que frequência',
  'admin.nav.types': 'Tipos',
  'admin.nav.types.hint': 'Categorias de equipamento',
  'admin.nav.history': 'Histórico',
  'admin.nav.history.hint': 'Trabalho concluído',
  'admin.nav.activity': 'Atividade',
  'admin.nav.activity.hint': 'Alterações de configuração',
  'admin.nav.theme.toLight': 'Mudar para o aspeto claro',
  'admin.nav.theme.toDark': 'Mudar para o aspeto escuro',
  'admin.nav.theme.toggle': 'Mudar o aspeto',
  'admin.nav.timezone.hint': 'Todas as datas previstas são calculadas neste fuso horário',
  'admin.nav.role': 'Administrador',
  'admin.nav.closeMenu': 'Fechar menu',

  /* ----------------------------------- admin/components/primitives.tsx --- */
  'admin.common.panel.open': 'Abrir',
  'admin.common.taskRow.hidden': 'Oculta — desativada',
  'admin.common.taskRow.reschedule': 'Reagendar esta tarefa',
  'admin.common.completion.noNote': 'Sem nota',

  /* -------------------------------- admin/components/EquipmentForm.tsx --- */
  'admin.equipmentForm.add': 'Adicionar equipamento',
  'admin.equipmentForm.edit': 'Editar equipamento',
  'admin.equipmentForm.save': 'Guardar alterações',
  'admin.equipmentForm.subtitle': 'Um registo por equipamento físico',
  'admin.equipmentForm.code': 'Código do ativo',
  'admin.equipmentForm.code.placeholder': 'AVAC-06',
  'admin.equipmentForm.code.hint': 'Único em todo o parque de equipamentos. É o que os técnicos procuram na etiqueta.',
  'admin.equipmentForm.name': 'Nome',
  'admin.equipmentForm.name.placeholder': 'Unidade de cobertura — ala este',
  'admin.equipmentForm.type': 'Tipo de equipamento',
  'admin.equipmentForm.type.hint': 'O equipamento herda todas as tarefas de manutenção definidas para este tipo.',
  'admin.equipmentForm.type.hintChanging': 'Alterar o tipo abre a agenda do novo tipo. O trabalho pendente de manutenções que deixam de se aplicar fica suspenso, mantendo a data que tem — nada é eliminado e, se voltar a colocar o equipamento no tipo anterior, é reposto. O histórico nunca é alterado.',
  'admin.equipmentForm.location': 'Localização',
  'admin.equipmentForm.location.placeholder': 'Cobertura, ala norte',
  'admin.equipmentForm.location.hint': 'Opcional. É mostrada aos técnicos para encontrarem o equipamento.',
  'admin.equipmentForm.active.on': 'Em serviço',
  'admin.equipmentForm.active.off': 'Desativado',
  'admin.equipmentForm.active.onHint': 'As manutenções deste equipamento aparecem na aplicação dos técnicos.',
  'admin.equipmentForm.active.offHint': 'As tarefas pendentes ficam ocultas e mantêm as datas. O histórico é preservado.',
  'admin.equipmentForm.customDue': 'Definir manualmente a primeira data prevista',
  'admin.equipmentForm.customDue.onHint': 'A primeira ocorrência de todas as tarefas herdadas fica prevista para a data abaixo.',
  'admin.equipmentForm.customDue.offHint': 'Por predefinição, a primeira ocorrência de cada tarefa fica prevista para daqui a um intervalo.',
  'admin.equipmentForm.firstDue': 'Primeira data prevista',
  'admin.equipmentForm.preview.inherits': { one: 'Este equipamento vai herdar 1 manutenção', other: 'Este equipamento vai herdar {count} manutenções' },
  'admin.equipmentForm.preview.emptyTitle': 'Este tipo ainda não tem manutenções ativas',
  'admin.equipmentForm.preview.firstDue': 'prevista para {date}',
  'admin.equipmentForm.preview.emptyHint': 'Pode adicionar manutenções ao tipo a qualquer momento — abrem automaticamente uma agenda neste equipamento.',
  'admin.equipmentForm.toast.updated': 'Equipamento atualizado',
  'admin.equipmentForm.toast.updatedBody': '{code} — {name}',
  'admin.equipmentForm.toast.added': '{code} adicionado',
  'admin.equipmentForm.toast.tasksScheduled': { one: '1 manutenção agendada para este equipamento.', other: '{count} manutenções agendadas para este equipamento.' },
  'admin.equipmentForm.toast.noTasks': 'Este tipo ainda não tem manutenções.',

  /* ------------------------------------- admin/components/RuleForm.tsx --- */
  'admin.ruleForm.preset.weekly': 'Semanal',
  'admin.ruleForm.preset.fortnightly': 'Quinzenal',
  'admin.ruleForm.preset.monthly': 'Mensal',
  'admin.ruleForm.preset.quarterly': 'Trimestral',
  'admin.ruleForm.preset.twiceAYear': 'Semestral',
  'admin.ruleForm.preset.yearly': 'Anual',
  'admin.ruleForm.toast.updated': 'Manutenção atualizada',
  'admin.ruleForm.toast.frequencyBody': 'A nova frequência aplica-se à próxima tarefa. As datas previstas pendentes mantêm-se.',
  'admin.ruleForm.toast.added': '«{title}» adicionada',
  'admin.ruleForm.toast.scheduled': { one: 'Ficou agendada em 1 equipamento deste tipo.', other: 'Ficou agendada em {count} equipamentos deste tipo.' },
  'admin.ruleForm.toast.noEquipment': 'Ainda não há equipamentos deste tipo — será agendada assim que adicionar algum.',
  'admin.ruleForm.saveFailed': 'Não foi possível guardar. Tente novamente.',
  'admin.ruleForm.title.edit': 'Editar manutenção',
  'admin.ruleForm.title.new': 'Nova manutenção',
  'admin.ruleForm.subtitle': 'Para cada {type}',
  'admin.ruleForm.saveChanges': 'Guardar alterações',
  'admin.ruleForm.submit': 'Adicionar manutenção',
  'admin.ruleForm.appliesTo': 'Aplica-se a',
  'admin.ruleForm.typeOption': { one: '{name} — 1 equipamento', other: '{name} — {count} equipamentos' },
  'admin.ruleForm.appliesToHint': 'Aplica-se a todos os equipamentos deste tipo, cada um com a sua própria agenda.',
  'admin.ruleForm.titleField': 'O que é preciso fazer',
  'admin.ruleForm.titlePlaceholder': 'Substituir filtros de ar',
  'admin.ruleForm.instructions': 'Instruções',
  'admin.ruleForm.instructionsPlaceholder': 'Escreva como explicaria a alguém que faz isto pela primeira vez.',
  'admin.ruleForm.instructionsHint': 'Aparece ao técnico no telemóvel, logo acima do formulário de conclusão.',
  'admin.ruleForm.howOften': 'Com que frequência',
  'admin.ruleForm.everyPrefix': 'A cada',
  'admin.ruleForm.intervalValue': 'Valor do intervalo',
  'admin.ruleForm.intervalUnit': 'Unidade do intervalo',
  'admin.ruleForm.cadenceEcho': '{cadence} — após cada conclusão, a tarefa seguinte fica prevista para um intervalo a contar do dia em que o trabalho foi efetivamente feito.',
  'admin.ruleForm.active': 'Ativa',
  'admin.ruleForm.deactivated': 'Desativada',
  'admin.ruleForm.activeHint': 'Aparece na aplicação do técnico para todos os equipamentos deste tipo.',
  'admin.ruleForm.deactivatedHint': 'As tarefas pendentes ficam ocultas e mantêm as datas. O histórico é preservado.',
  'admin.ruleForm.frequencyChange': 'Alteração da frequência',
  'admin.ruleForm.frequencyChangeBody': 'As tarefas pendentes mantêm as datas previstas que já têm. O novo intervalo passa a aplicar-se à próxima tarefa gerada após uma conclusão. Para alterar agora uma tarefa pendente, reagende-a explicitamente.',
  'admin.ruleForm.customDue': 'Definir manualmente a primeira data prevista',
  'admin.ruleForm.customDueOn': 'Em todos os equipamentos deste tipo, a primeira tarefa fica prevista para a data abaixo.',
  'admin.ruleForm.customDueOff': 'Por predefinição, a primeira tarefa fica prevista para {date}.',
  'admin.ruleForm.firstDueDate': 'Primeira data prevista',
  'admin.ruleForm.previewCount': { one: '1 equipamento existente fica com esta tarefa na agenda', other: '{count} equipamentos existentes ficam com esta tarefa na agenda' },
  'admin.ruleForm.previewNone': 'Ainda não há equipamentos deste tipo',
  'admin.ruleForm.previewBody': 'Cada um mantém a sua própria agenda independente, com a primeira data prevista para {date}. Não são inventadas conclusões passadas.',
  'admin.ruleForm.previewNoneBody': 'Adicione um equipamento deste tipo e ele passa a ter esta tarefa automaticamente.',

  /* ----------------------------- admin/components/RescheduleDialog.tsx --- */
  'admin.reschedule.title': 'Reagendar esta tarefa',
  'admin.reschedule.confirm': 'Mover esta tarefa',
  'admin.reschedule.currentlyDue': 'Atualmente prevista para {date}',
  'admin.reschedule.shortcut.today': 'Hoje',
  'admin.reschedule.shortcut.tomorrow': 'Amanhã',
  'admin.reschedule.shortcut.week': 'Em 1 semana',
  'admin.reschedule.shortcut.month': 'Em 1 mês',
  'admin.reschedule.newDate': 'Nova data prevista',
  'admin.reschedule.reason': 'Motivo',
  'admin.reschedule.reason.placeholder': 'Peças encomendadas, prestador indisponível, fábrica encerrada…',
  'admin.reschedule.reason.hint': 'Opcional — mas é o que faz com que valha a pena ler o registo de atividade mais tarde.',
  'admin.reschedule.note': 'Isto move apenas esta tarefa, neste equipamento. Depois de o trabalho ser concluído, a tarefa seguinte continua a ser calculada a partir do dia em que foi efetivamente realizado.',
  'admin.reschedule.toast.done': 'Tarefa reagendada',
  'admin.reschedule.toast.doneBody': '{rule} em {equipment} tem agora data prevista para {date}.',
  'admin.reschedule.toast.noChange': 'Nada a alterar',
  'admin.reschedule.toast.noChangeBody': 'A tarefa já está prevista para esta data ou acabou de ser concluída.',
  'admin.reschedule.toast.failed': 'Não foi possível reagendar',

  /* -------------------------------- admin/components/ArchiveDialog.tsx --- */
  'admin.archive.title': 'Arquivar {name}?',
  'admin.archive.subtitle.equipment': 'Este equipamento deixará de aparecer nos locais onde se configura o trabalho.',
  'admin.archive.subtitle.rule': 'Esta manutenção deixará de aparecer nos locais onde se configura o trabalho.',
  'admin.archive.subtitle.type': 'Este tipo de equipamento deixará de aparecer nos locais onde se configura o trabalho.',
  'admin.archive.records': { one: '1 registo de conclusão mantém-se exatamente como está.', other: '{count} registos de conclusão mantêm-se exatamente como estão.' },
  'admin.archive.recordsWhy': { one: 'Guarda a sua própria cópia dos dados, pelo que arquivar não pode alterar o que diz.', other: 'Cada um guarda a sua própria cópia dos dados, pelo que arquivar não pode alterar o que dizem.' },
  'admin.archive.pending': { one: '1 tarefa pendente ficará oculta.', other: '{count} tarefas pendentes ficarão ocultas.' },
  'admin.archive.pendingKept': { one: 'Não é eliminada.', other: 'Não são eliminadas.' },
  'admin.archive.nothingDeleted': 'Nada é removido da base de dados. Arquivar é a forma como este sistema retira de serviço algo que o histórico ainda referencia.',
  'admin.archive.keep': 'Manter',
  'admin.archive.confirm': 'Arquivar',
  'admin.archive.done': '{name} arquivado',
  'admin.archive.doneBody': 'O histórico de conclusões fica intacto e continua acessível.',
  'admin.archive.failed': 'Não foi possível arquivar',

  /* ------------------------------ admin/components/CompletionSheet.tsx --- */
  'admin.completion.title': 'Manutenção concluída',
  'admin.completion.photoAlt': 'Fotografia enviada para a tarefa {task} no equipamento {equipment}',
  'admin.completion.submittedBy': 'Enviada por {name}',
  'admin.completion.fact.equipmentType': 'Tipo de equipamento',
  'admin.completion.fact.scheduledFor': 'Prevista para',
  'admin.completion.fact.completed': 'Concluída',
  'admin.completion.fact.punctuality': 'Pontualidade',
  'admin.completion.fact.carriedOutBy': 'Realizada por',
  'admin.completion.fact.frequency': 'Frequência na altura',
  'admin.completion.punctuality.onTheDay': 'No dia previsto',
  'admin.completion.punctuality.early': { one: '1 dia de antecedência', other: '{count} dias de antecedência' },
  'admin.completion.punctuality.late': { one: '1 dia de atraso', other: '{count} dias de atraso' },
  'admin.completion.note': 'Nota do técnico',
  'admin.completion.noNote': 'Não foi deixado nenhum comentário.',
  'admin.completion.instructions': 'Instruções tal como estavam na altura',
  'admin.completion.immutable': 'Este registo é permanente. Guarda os dados do equipamento e da manutenção tal como estavam nesse dia, independentemente do que tenha mudado entretanto.',

  /* ------------------------------------------ admin/screens/SignIn.tsx --- */
  'admin.signIn.lede': 'Inicie sessão para configurar equipamentos, acompanhar a agenda e rever o trabalho concluído.',
  'admin.signIn.email': 'Email',
  'admin.signIn.email.placeholder': 'nome@empresa.com',
  'admin.signIn.password': 'Palavra-passe',
  'admin.signIn.workerHint': 'Os técnicos iniciam sessão na sua própria aplicação. Esta destina-se apenas a administradores.',
  'admin.signIn.demo': 'Administrador de demonstração —',

  /* --------------------------------------- admin/screens/Dashboard.tsx --- */
  'admin.dashboard.title': 'Vista geral',
  'admin.dashboard.lede.estate': { one: '1 equipamento ativo em {types}', other: '{count} equipamentos ativos em {types}' },
  'admin.dashboard.lede.types': { one: '1 tipo', other: '{count} tipos' },
  'admin.dashboard.refresh': 'Atualizar',
  'admin.dashboard.refreshing': 'A atualizar',
  'admin.dashboard.tile.equipment.label': 'Equipamentos ativos',
  'admin.dashboard.tile.equipment.deactivated': { one: '1 equipamento desativado', other: '{count} equipamentos desativados' },
  'admin.dashboard.tile.equipment.allActive': 'Todos em serviço',
  'admin.dashboard.tile.overdue.oldest': { one: 'Mais antiga: 1 dia de atraso', other: 'Mais antiga: {count} dias de atraso' },
  'admin.dashboard.tile.overdue.none': 'Nada em atraso',
  'admin.dashboard.tile.today.scheduled': 'Agendado para {date}',
  'admin.dashboard.tile.today.none': 'Nada agendado para hoje',
  'admin.dashboard.tile.week.label': 'Próximos 7 dias',
  'admin.dashboard.tile.week.outstanding': { one: '1 tarefa pendente no total', other: '{count} tarefas pendentes no total' },
  'admin.dashboard.load.title': 'As próximas duas semanas',
  'admin.dashboard.load.pressure': { one: '1 tarefa precisa de atenção hoje ou antes', other: '{count} tarefas precisam de atenção hoje ou antes' },
  'admin.dashboard.load.clear': 'Nada em atraso — a agenda está livre',
  'admin.dashboard.load.open': 'Abrir a lista de tarefas',
  'admin.dashboard.load.empty.title': 'Não há nada agendado',
  'admin.dashboard.load.empty.body': 'Todos os equipamentos estão desativados ou não têm nenhuma manutenção ativa. Adicione uma e a agenda aparece aqui.',
  'admin.dashboard.load.empty.action': 'Adicionar manutenção',
  'admin.dashboard.setup.title': 'Ainda não há nada configurado',
  'admin.dashboard.setup.body': 'Comece por um tipo de equipamento, defina a manutenção de que precisa e depois adicione os equipamentos físicos. Cada um fica com a sua própria agenda.',
  'admin.dashboard.setup.action': 'Criar o primeiro tipo',
  'admin.dashboard.load.scale': 'Tarefas previstas por dia',
  'admin.dashboard.load.peak': { one: '{count} no pico', other: '{count} no pico' },
  'admin.dashboard.load.axisToday': 'Hoje',
  'admin.dashboard.load.tip': { one: '{weekday} {date}: 1 tarefa', other: '{weekday} {date}: {count} tarefas' },
  'admin.dashboard.load.tipCarried': { one: '{date}: 1 tarefa prevista, incluindo {carried} em atraso', other: '{date}: {count} tarefas previstas, incluindo {carried} em atraso' },
  'admin.dashboard.ontime.title': 'Taxa de pontualidade',
  'admin.dashboard.ontime.subtitle': 'Concluídas até à data prevista, últimos trinta dias',
  'admin.dashboard.ontime.open': 'Ver histórico',
  'admin.dashboard.ontime.met': { one: '{onTime} de 1 conclusão cumpriu a data prevista', other: '{onTime} de {count} conclusões cumpriram a data prevista' },
  'admin.dashboard.ontime.total': { one: '1 conclusão registada no total', other: '{count} conclusões registadas no total' },
  'admin.dashboard.ontime.spark': 'Atividade de 28 dias',
  'admin.dashboard.attention.title': 'Requer atenção',
  'admin.dashboard.attention.subtitle': { one: '1 tarefa em atraso', other: '{count} tarefas em atraso' },
  'admin.dashboard.attention.none': 'Nada em atraso',
  'admin.dashboard.attention.open': 'Ver tarefas em atraso',
  'admin.dashboard.attention.empty.title': 'Está tudo em dia',
  'admin.dashboard.attention.empty.body': 'Nenhuma manutenção passou da data prevista. As próximas estão agendadas abaixo.',
  'admin.dashboard.recent.title': 'Concluídas recentemente',
  'admin.dashboard.recent.subtitle': 'Enviado pela aplicação dos técnicos',
  'admin.dashboard.recent.open': 'Histórico completo',
  'admin.dashboard.recent.empty.title': 'Ainda sem conclusões',
  'admin.dashboard.recent.empty.body': 'O trabalho enviado pela equipa aparece aqui, com fotografia e tudo.',
  'admin.dashboard.types.title': 'Tipos de equipamento',
  'admin.dashboard.types.subtitle': { one: '1 tipo · {tasks}', other: '{count} tipos · {tasks}' },
  'admin.dashboard.types.tasks': { one: '1 manutenção ativa', other: '{count} manutenções ativas' },
  'admin.dashboard.types.open': 'Gerir tipos',
  'admin.dashboard.next.title': 'A seguir',
  'admin.dashboard.next.subtitle': 'O próximo trabalho agendado',
  'admin.dashboard.next.open': 'Ver a agenda',
  'admin.dashboard.next.empty.title': 'Nada agendado',
  'admin.dashboard.next.empty.body': 'Adicione equipamento ou uma manutenção para criar uma agenda.',
  'admin.dashboard.hidden.body': { one: '1 tarefa pendente está oculta porque a manutenção ou o equipamento correspondente está desativado. Mantém a data prevista e reaparece logo após a reativação.', other: '{count} tarefas pendentes estão ocultas porque a manutenção ou o equipamento correspondente está desativado. Mantêm as datas previstas e reaparecem logo após a reativação.' },
  'admin.dashboard.hidden.action': 'Mostrar tarefas',

  /* --------------------------------------- admin/screens/TaskBoard.tsx --- */
  'admin.tasks.title': 'Trabalho pendente',
  'admin.tasks.outstandingCount': { one: '1 tarefa pendente', other: '{count} tarefas pendentes' },
  'admin.tasks.loading': 'A carregar a agenda…',
  'admin.tasks.refresh': 'Atualizar',
  'admin.tasks.bucket.all': 'Tudo',
  'admin.tasks.filter.status': 'Filtrar por estado da data prevista',
  'admin.tasks.filter.dueOn': 'Prevista para {date}',
  'admin.tasks.filter.clearDate': 'Limpar o filtro de data',
  'admin.tasks.search.placeholder': 'Pesquisar código do ativo, nome, localização ou tarefa',
  'admin.tasks.search.label': 'Pesquisar no trabalho pendente',
  'admin.tasks.search.clear': 'Limpar a pesquisa',
  'admin.tasks.filter.type': 'Filtrar por tipo de equipamento',
  'admin.tasks.filter.allTypes': 'Todos os tipos',
  'admin.tasks.filter.equipment': 'Filtrar por equipamento',
  'admin.tasks.filter.allEquipment': 'Todos os equipamentos',
  'admin.tasks.includeHidden': 'Incluir ocultas',
  'admin.tasks.empty.title': 'Sem trabalho pendente',
  'admin.tasks.empty.body': 'Todas as tarefas agendadas foram concluídas. Surgem novas tarefas à medida que chega a data prevista.',
  'admin.tasks.empty.filtered': 'Nada corresponde a estes filtros',
  'admin.tasks.empty.filteredBody': 'Experimente alargar a pesquisa ou limpe os filtros para ver toda a agenda.',
  'admin.tasks.empty.clearFilters': 'Limpar filtros',
  'admin.tasks.truncated': 'A mostrar as {shown} tarefas mais urgentes de {total} pendentes — os totais acima incluem-nas todas. Filtre por tipo ou equipamento, ou pesquise, para chegar às restantes.',

  /* ----------------------------------- admin/screens/EquipmentList.tsx --- */
  'admin.equipment.title': 'Equipamento',
  'admin.equipment.lede.count': { one: '{count} item apresentado · um registo por cada objeto físico existente no local', other: '{count} itens apresentados · um registo por cada objeto físico existente no local' },
  'admin.equipment.lede.loading': 'A carregar o parque de equipamentos…',
  'admin.equipment.add': 'Adicionar equipamento',
  'admin.equipment.filter.scope': 'Filtrar por estado',
  'admin.equipment.scope.active': 'Em serviço',
  'admin.equipment.scope.inactive': 'Desativados',
  'admin.equipment.scope.all': 'Tudo',
  'admin.equipment.search.placeholder': 'Pesquisar código, nome ou localização',
  'admin.equipment.search.aria': 'Pesquisar equipamentos',
  'admin.equipment.search.clear': 'Limpar pesquisa',
  'admin.equipment.filter.type': 'Filtrar por tipo',
  'admin.equipment.filter.allTypes': 'Todos os tipos',
  'admin.equipment.filter.typeOption': '{name} ({count})',
  'admin.equipment.empty.title': 'Ainda sem equipamentos',
  'admin.equipment.empty.body': 'Adicione o primeiro equipamento e este herdará todas as tarefas de manutenção definidas para o respetivo tipo.',
  'admin.equipment.empty.filtered.title': 'Sem resultados',
  'admin.equipment.empty.filtered.body': 'Experimente outra pesquisa ou limpe o filtro de tipo.',
  'admin.equipment.card.deactivated': 'Desativado',
  'admin.equipment.card.noLocation': 'Sem localização registada',
  'admin.equipment.card.scheduled': { one: 'agendada', other: 'agendadas' },
  'admin.equipment.card.completed': { one: 'concluída', other: 'concluídas' },
  'admin.equipment.card.next': 'Próx. {date}',
  'admin.equipment.card.noSchedule': 'Sem agenda',
  'admin.equipment.card.lastServiced': 'Última intervenção {when}',
  'admin.equipment.card.neverServiced': 'Sem intervenções',

  /* --------------------------------- admin/screens/EquipmentDetail.tsx --- */
  'admin.equipmentDetail.backToEquipment': 'Equipamentos',
  'admin.equipmentDetail.flag.deactivated': 'Desativado',
  'admin.equipmentDetail.rule.deactivatedFlag': 'Desativada',
  'admin.equipmentDetail.noLocation': 'Sem localização registada',
  'admin.equipmentDetail.lastServiced': 'Última intervenção {when}',
  'admin.equipmentDetail.neverServiced': 'Sem intervenções',
  'admin.equipmentDetail.stat.scheduled': 'Agendadas',
  'admin.equipmentDetail.stat.completed': 'Concluídas',
  'admin.equipmentDetail.stat.nextDue': 'Próxima',
  'admin.equipmentDetail.action.edit': 'Editar',
  'admin.equipmentDetail.action.duplicate': 'Duplicar',
  'admin.equipmentDetail.action.deactivate': 'Desativar',
  'admin.equipmentDetail.action.reactivate': 'Reativar',
  'admin.equipmentDetail.action.archive': 'Arquivar',
  'admin.equipmentDetail.tabs.aria': 'Secções de detalhe do equipamento',
  'admin.equipmentDetail.tab.schedule': 'Agenda',
  'admin.equipmentDetail.tab.history': 'Histórico',
  'admin.equipmentDetail.tab.activity': 'Atividade',
  'admin.equipmentDetail.reactivated': 'Novamente em serviço',
  'admin.equipmentDetail.reactivatedBody': 'As tarefas pendentes voltam a estar visíveis, com as datas previstas que já tinham.',
  'admin.equipmentDetail.deactivated': 'Desativado',
  'admin.equipmentDetail.deactivatedBody': 'As tarefas pendentes ficam ocultas e mantêm as datas. O histórico de conclusões não é alterado.',
  'admin.equipmentDetail.updateFailed': 'Não foi possível atualizar',
  'admin.equipmentDetail.empty.scheduleTitle': 'Sem manutenções agendadas',
  'admin.equipmentDetail.empty.scheduleBody': 'Adicione uma manutenção a este tipo de equipamento e a agenda aparece aqui automaticamente.',
  'admin.equipmentDetail.empty.addTask': 'Adicionar manutenção',
  'admin.equipmentDetail.empty.hiddenTitle': 'Agenda oculta enquanto estiver desativado',
  'admin.equipmentDetail.empty.hiddenBody': 'As tarefas pendentes continuam a existir e mantêm as datas previstas. Reative o equipamento para as voltar a mostrar.',
  'admin.equipmentDetail.empty.historyTitle': 'Ainda sem trabalhos concluídos',
  'admin.equipmentDetail.empty.historyBody': 'As conclusões enviadas pela aplicação dos técnicos aparecem aqui, com a fotografia, a pessoa e a hora exata.',
  'admin.equipmentDetail.empty.activityTitle': 'Sem alterações registadas',
  'admin.equipmentDetail.empty.activityBody': 'As alterações de configuração e os reagendamentos deste equipamento são listados aqui.',
  'admin.equipmentDetail.hiddenNote': { one: '1 tarefa pendente está oculta porque a manutenção ou o equipamento está desativado. As datas são preservadas.', other: '{count} tarefas pendentes estão ocultas porque a manutenção ou o equipamento está desativado. As datas são preservadas.' },
  'admin.equipmentDetail.inheritedFrom': 'Herdadas de {type}',
  'admin.equipmentDetail.duplicated': { one: '{code} criado', other: '{count} novos equipamentos criados' },
  'admin.equipmentDetail.duplicatedBody': 'Cada um tem um novo identificador e uma agenda nova. Não foi copiado nenhum histórico.',
  'admin.equipmentDetail.duplicate.title': 'Duplicar este equipamento',
  'admin.equipmentDetail.duplicate.subtitle': 'Com base em {code}',
  'admin.equipmentDetail.duplicate.note': 'Um duplicado é um novo equipamento físico: recebe o seu próprio código do ativo e uma agenda nova que começa hoje. O histórico de conclusões nunca é copiado — pertence ao original.',
  'admin.equipmentDetail.duplicate.codeLabel': 'Código do ativo',
  'admin.equipmentDetail.duplicate.hintOne': 'Deixe em branco para acrescentar -COPY ao código original.',
  'admin.equipmentDetail.duplicate.hintMany': 'É acrescentado um sufixo de dois dígitos a cada cópia.',
  'admin.equipmentDetail.duplicate.countLabel': 'Quantidade',
  'admin.equipmentDetail.duplicate.firstDue': 'A primeira tarefa de cada cópia fica prevista para um intervalo após {date}.',
  'admin.equipmentDetail.duplicate.submit': { one: 'Criar uma cópia', other: 'Criar {count} cópias' },
  'admin.equipmentDetail.duplicate.failed': 'Não foi possível duplicar',

  /* ---------------------------------------- admin/screens/RuleList.tsx --- */
  'admin.rules.title': 'Manutenção',
  'admin.rules.lede': { one: '1 manutenção em {types} · cada equipamento de um tipo mantém a sua própria agenda', other: '{count} manutenções em {types} · cada equipamento de um tipo mantém a sua própria agenda' },
  'admin.rules.lede.types': { one: '1 tipo de equipamento', other: '{count} tipos de equipamento' },
  'admin.rules.add': 'Nova manutenção',
  'admin.rules.filter.scope': 'Filtrar por estado',
  'admin.rules.scope.all': 'Tudo',
  'admin.rules.scope.active': 'Ativas',
  'admin.rules.scope.inactive': 'Inativas',
  'admin.rules.filter.type': 'Filtrar por tipo',
  'admin.rules.filter.allTypes': 'Todos os tipos',
  'admin.rules.filter.typeOption': '{name} ({count})',
  'admin.rules.empty.filtered.title': 'Sem resultados',
  'admin.rules.empty.filtered.body': 'Experimente limpar os filtros.',
  'admin.rules.empty.title': 'Ainda sem manutenções definidas',
  'admin.rules.empty.body': 'Defina o que é preciso fazer e com que frequência. Todos os equipamentos do tipo escolhido ficam abrangidos de imediato.',
  'admin.rules.group.count': { one: '1 manutenção', other: '{count} manutenções' },
  'admin.rules.group.add': 'Adicionar',
  'admin.rules.card.deactivated': 'Inativa',
  'admin.rules.card.noInstructions': 'Ainda sem instruções.',
  'admin.rules.card.scheduled': { one: '1 agendada', other: '{count} agendadas' },
  'admin.rules.card.completions': { one: '1 conclusão', other: '{count} conclusões' },

  /* -------------------------------------- admin/screens/RuleDetail.tsx --- */
  'admin.ruleDetail.backToRules': 'Manutenção',
  'admin.ruleDetail.reactivated': 'Reativada',
  'admin.ruleDetail.reactivatedBody': 'As tarefas pendentes voltam a ficar visíveis nas datas previstas que já tinham, incluindo as que estão em atraso.',
  'admin.ruleDetail.deactivated': 'Desativada',
  'admin.ruleDetail.deactivatedBody': 'As tarefas pendentes ficam ocultas e mantêm as datas. O histórico de conclusões não é alterado.',
  'admin.ruleDetail.updateFailed': 'Não foi possível atualizar',
  'admin.ruleDetail.flag.deactivated': 'Inativa',
  'admin.ruleDetail.noInstructions': 'Ainda sem instruções — os técnicos veem apenas o título.',
  'admin.ruleDetail.stat.scheduled': 'Agendadas',
  'admin.ruleDetail.stat.completed': 'Concluídas',
  'admin.ruleDetail.action.edit': 'Editar',
  'admin.ruleDetail.action.deactivate': 'Desativar',
  'admin.ruleDetail.action.reactivate': 'Reativar',
  'admin.ruleDetail.action.archive': 'Arquivar',
  'admin.ruleDetail.tabs.aria': 'Secções',
  'admin.ruleDetail.tab.schedule': 'Agenda',
  'admin.ruleDetail.tab.history': 'Histórico',
  'admin.ruleDetail.tab.activity': 'Atividade',
  'admin.ruleDetail.empty.scheduleTitle': 'Ainda sem equipamentos deste tipo',
  'admin.ruleDetail.empty.scheduleBody': 'Adicione equipamentos deste tipo e cada um herda esta manutenção, com uma agenda própria.',
  'admin.ruleDetail.empty.hiddenTitle': 'Agendas ocultas enquanto estiver desativada',
  'admin.ruleDetail.empty.hiddenBody': 'Todas as tarefas pendentes continuam a existir e mantêm a data. Reative para as voltar a mostrar.',
  'admin.ruleDetail.empty.seeEquipment': 'Ver equipamentos',
  'admin.ruleDetail.hiddenNote': { one: '1 tarefa está oculta porque o respetivo equipamento está desativado. A data mantém-se.', other: '{count} tarefas estão ocultas porque os respetivos equipamentos estão desativados. As datas mantêm-se.' },
  'admin.ruleDetail.empty.historyTitle': 'Ainda não foi concluída',
  'admin.ruleDetail.empty.historyBody': 'Assim que esta manutenção for realizada, cada conclusão aparece aqui com a respetiva fotografia.',
  'admin.ruleDetail.empty.activityTitle': 'Sem alterações registadas',

  /* ---------------------------------------- admin/screens/TypeList.tsx --- */
  'admin.types.title': 'Tipos de equipamento',
  'admin.types.lede': 'Defina a manutenção uma vez por tipo. Todos os equipamentos desse tipo herdam-na, cada um com a sua agenda.',
  'admin.types.add': 'Novo tipo',
  'admin.types.empty.title': 'Ainda não há tipos de equipamento',
  'admin.types.empty.body': 'Comece por um tipo — “Unidade AVAC”, “Empilhador”, “Extintor” — e depois defina a manutenção necessária.',
  'admin.types.toast.archived': 'Tipo arquivado',
  'admin.types.toast.archivedBody': 'O histórico é preservado e continua acessível.',
  'admin.types.toast.archiveFailed': 'Não foi possível arquivar',
  'admin.types.card.edit': 'Editar {name}',
  'admin.types.card.inService': { one: 'em serviço', other: 'em serviço' },
  'admin.types.card.equipmentDeactivated': { one: '{count} desativado', other: '{count} desativados' },
  'admin.types.card.tasks': { one: 'tarefa', other: 'tarefas' },
  'admin.types.card.tasksDeactivated': { one: '{count} desativada', other: '{count} desativadas' },
  'admin.types.card.equipmentLink': 'Equipamento',
  'admin.types.card.maintenanceLink': 'Manutenção',
  'admin.types.toast.updated': 'Tipo atualizado',
  'admin.types.toast.added': '“{name}” adicionado',
  'admin.types.toast.addedBody': 'Defina agora a manutenção necessária.',
  'admin.types.form.saveFailed': 'Não foi possível guardar. Tente novamente.',
  'admin.types.form.editTitle': 'Editar tipo de equipamento',
  'admin.types.form.newTitle': 'Novo tipo de equipamento',
  'admin.types.form.archive': 'Arquivar',
  'admin.types.form.save': 'Guardar alterações',
  'admin.types.form.create': 'Criar tipo',
  'admin.types.form.name': 'Nome',
  'admin.types.form.namePlaceholder': 'Unidade AVAC',
  'admin.types.form.colour': 'Cor',
  'admin.types.form.symbol': 'Símbolo',
  'admin.types.form.archiveNote': 'Ao arquivar, o tipo e as respetivas tarefas de manutenção ficam ocultos. Só é possível quando nenhum equipamento o utiliza. O histórico das conclusões mantém-se sempre — guarda uma cópia própria dos detalhes.',
  'admin.types.accent.aurora': 'Aurora',
  'admin.types.accent.ice': 'Gelo',
  'admin.types.accent.cobalt': 'Cobalto',
  'admin.types.accent.orchid': 'Orquídea',
  'admin.types.accent.ember': 'Brasa',
  'admin.types.accent.sunset': 'Pôr do sol',
  'admin.types.accent.gold': 'Dourado',
  'admin.types.accent.lime': 'Verde-lima',
  'admin.types.symbol.cube': 'Cubo',
  'admin.types.symbol.fan': 'Ventoinha',
  'admin.types.symbol.bolt': 'Raio',
  'admin.types.symbol.drop': 'Gota',
  'admin.types.symbol.gear': 'Roda dentada',
  'admin.types.symbol.flame': 'Chama',
  'admin.types.symbol.wave': 'Onda',
  'admin.types.symbol.shield': 'Escudo',
  'admin.types.symbol.truck': 'Camião',
  'admin.types.symbol.leaf': 'Folha',
  'admin.types.symbol.chip': 'Chip',
  'admin.types.symbol.lift': 'Elevador',

  /* ----------------------------------- admin/screens/HistoryScreen.tsx --- */
  'admin.history.title': 'Histórico de conclusões',
  'admin.history.lede.filtered': { one: '{count} tarefa concluída corresponde aos filtros · com fotografia', other: '{count} tarefas concluídas correspondem aos filtros · todas com fotografia' },
  'admin.history.lede.all': { one: '{count} tarefa concluída registada · com fotografia', other: '{count} tarefas concluídas registadas · todas com fotografia' },
  'admin.history.search.placeholder': 'Pesquisar equipamento, tarefa, pessoa ou comentário',
  'admin.history.search.aria': 'Pesquisar no histórico',
  'admin.history.search.clear': 'Limpar pesquisa',
  'admin.history.filter.type': 'Filtrar por tipo',
  'admin.history.filter.allTypes': 'Todos os tipos',
  'admin.history.filter.person': 'Filtrar por pessoa',
  'admin.history.filter.anyone': 'Todos',
  'admin.history.filter.fromDate': 'Data de início',
  'admin.history.filter.toDate': 'Data de fim',
  'admin.history.filter.rangeTo': 'a',
  'admin.history.range.last7': 'Últimos 7 dias',
  'admin.history.range.last30': 'Últimos 30 dias',
  'admin.history.empty.filtered.title': 'Nada corresponde a esses filtros',
  'admin.history.empty.filtered.body': 'Experimente alargar o intervalo de datas ou limpar os filtros.',
  'admin.history.empty.title': 'Ainda não há trabalho concluído',
  'admin.history.empty.body': 'Quando a equipa regista uma manutenção na aplicação dos técnicos, esta aparece aqui — fotografia, pessoa e a hora exata do registo.',
  'admin.history.empty.clearFilters': 'Limpar filtros',
  'admin.history.empty.seeTasks': 'Ver tarefas pendentes',
  'admin.history.showMore': { one: 'Mostrar mais 1', other: 'Mostrar mais {count}' },
  'admin.history.more.shown': 'A mostrar {shown} de {total}',
  'admin.history.more.shownRange': 'A mostrar {shown} de {total} · {from} a {to}',
  'admin.history.more.shownFrom': 'A mostrar {shown} de {total} · desde {from}',
  'admin.history.more.shownTo': 'A mostrar {shown} de {total} · até {to}',
  'admin.history.end': { one: 'Ao todo, {count} registo.', other: 'Ao todo, {count} registos.' },

  /* ---------------------------------- admin/screens/ActivityScreen.tsx --- */
  'admin.activity.title': 'Atividade',
  'admin.activity.lede': 'Todas as alterações de configuração e todos os reagendamentos, com indicação de quem os fez e quando.',
  'admin.activity.filter.aria': 'Filtrar atividade',
  'admin.activity.scope.all': 'Tudo',
  'admin.activity.scope.schedule': 'Reagendamentos',
  'admin.activity.scope.config': 'Configuração',
  'admin.activity.empty.title': 'Ainda não há registos',
  'admin.activity.empty.body': 'As alterações a equipamentos, tipos, tarefas de manutenção e agendas serão listadas aqui.',
  'admin.activity.detail.reason': '“{reason}”',

  /* ----------------------------------------- worker/screens/SignIn.tsx --- */
  'worker.signIn.lede': 'Inicie sessão para ver o que há para fazer hoje.',
  'worker.signIn.email': 'Email',
  'worker.signIn.email.placeholder': 'nome@empresa.com',
  'worker.signIn.password': 'Palavra-passe',
  'worker.signIn.demo': 'Demo —',

  /* --------------------------------------- worker/screens/TaskList.tsx --- */
  'worker.list.greeting.morning': 'Bom dia, {name}',
  'worker.list.greeting.afternoon': 'Boa tarde, {name}',
  'worker.list.greeting.evening': 'Boa noite, {name}',
  'worker.list.title.clear': 'Nada para hoje',
  'worker.list.title.toDo': { one: '1 por fazer', other: '{count} por fazer' },
  'worker.list.refresh': 'Atualizar a lista',
  'worker.list.toggleTheme': 'Mudar o aspeto',
  'worker.list.searchPlaceholder': 'Código do ativo, nome ou localização',
  'worker.list.searchLabel': 'Pesquisar tarefas',
  'worker.list.empty.noMatchTitle': 'Sem resultados',
  'worker.list.empty.noMatchBody': 'Experimente outro código do ativo ou outra localização.',
  'worker.list.empty.clearTitle': 'Tudo em dia',
  'worker.list.empty.clearBody': 'Todas as tarefas agendadas foram concluídas. As próximas aparecem aqui quando chegar a data prevista.',
  'worker.list.clearSearch': 'Limpar pesquisa',
  'worker.list.show': 'Mostrar',
  'worker.list.hide': 'Ocultar',
  'worker.list.truncated': { one: 'A mostrar a tarefa mais urgente ({shown} de 1). Pesquise para encontrar uma tarefa específica.', other: 'A mostrar as {shown} mais urgentes de {count} tarefas. Pesquise para encontrar uma tarefa específica.' },
  'worker.list.footer': { one: '1 tarefa pendente · horas em {zone}', other: '{count} tarefas pendentes · horas em {zone}' },

  /* ------------------------------------- worker/screens/TaskDetail.tsx --- */
  'worker.detail.allJobs': 'Tarefas',
  'worker.detail.gone': 'Esta tarefa já não está pendente.',
  'worker.detail.goneDetail': 'Pode ter sido concluída por outra pessoa ou ter sido desativada.',
  'worker.detail.backToList': 'Voltar à lista',
  'worker.detail.sessionEnded': 'A sua sessão terminou. Inicie sessão novamente e a tarefa continuará aqui.',
  'worker.detail.stillOpen': 'Algo correu mal. A tarefa continua em aberto — tente novamente.',
  'worker.detail.toast.alreadyDone': 'Já concluída',
  'worker.detail.toast.alreadyDoneBody': 'Outra pessoa submeteu esta tarefa. Esta é a lista atualizada.',
  'worker.detail.where': 'Local',
  'worker.detail.noLocation': 'Sem localização registada',
  'worker.detail.due': 'Prevista',
  'worker.detail.instructions': 'O que fazer',
  'worker.detail.finish': 'Concluir a tarefa',
  'worker.detail.check': 'Manutenção concluída',
  'worker.detail.photoHint': 'Uma fotografia do trabalho realizado. Fica guardada com o registo e só os administradores a podem ver.',
  'worker.detail.comment': 'Algo a acrescentar?',
  'worker.detail.comment.placeholder': 'Opcional — peças utilizadas, algo que tenha notado, o que valha a pena saber da próxima vez.',
  'worker.detail.missing.tick': 'Assinale primeiro “Manutenção concluída”',
  'worker.detail.missing.photo': 'Adicione uma fotografia do trabalho',
  'worker.detail.submitting': 'A enviar…',
  'worker.detail.submit': 'Enviar conclusão',
  'worker.detail.submit.progress': { one: 'Enviar — {count} de 2 pronto', other: 'Enviar — {count} de 2 prontos' },

  /* ------------------------------ worker/components/SuccessOverlay.tsx --- */
  'worker.success.title': 'Registado. Boa!',
  'worker.success.next': 'Próxima: {date}',
  'worker.success.inDays': { one: 'daqui a 1 dia', other: 'daqui a {count} dias' },
  'worker.success.backToList': 'Voltar à lista',
};
